In [2]:
import numpy as np
import pandas as pd
import sklearn
import requests
from tqdm import tqdm

# Load Data

In [3]:
username = "2wsgzl0-vwx2hipkj-yxme0ub-wgjenczp83"
password = "nQv7vWe@FtES5_Z%4@F^GbtZrA*&Rh"

matches_data = requests.get("https://apirest.wyscout.com/v3/competitions?areaId=USA", auth=(username, password))
comp_df = pd.DataFrame(matches_data.json()['competitions'])
matches_df = pd.DataFrame()
for i in tqdm(comp_df['wyId'].tolist()):
    league_data = requests.get(f"https://apirest.wyscout.com/v3/competitions/{i}/matches", auth=(username, password))
    mdf = pd.DataFrame(league_data.json()['matches'])
    matches_df = pd.concat([matches_df, mdf])
matches_df.head()

100%|██████████| 33/33 [00:20<00:00,  1.57it/s]

,matchId,label,date,dateutc,status,competitionId,seasonId,roundId,gameweek
0,5539787,"Bryant Bulldogs - Chicago State Cougars, 5-2",2023-10-20 01:00:00,2023-10-19 23:00:00,Played,43259,190032,4429616,3
1,5539502,"USC Upstate Spartans - SCSU Bulldogs, 10-0",2023-10-19 00:00:00,2023-10-18 22:00:00,Played,43259,190032,4429616,3
2,5512618,"Boston Terriers - Yale Bulldogs, 1-1",2023-10-18 01:00:00,2023-10-17 23:00:00,Played,43259,190032,4429616,3
3,5512619,"Princeton Tigers - Bucknell Bison, 0-1",2023-10-18 01:00:00,2023-10-17 23:00:00,Played,43259,190032,4429616,3
4,5512617,"Cornell Big Red - Albany Great Danes, 4-0",2023-10-17 23:00:00,2023-10-17 21:00:00,Played,43259,190032,4429616,3

# Feature Engineering on Event Data from One Match

## Load Match Event Data

In [4]:
event_data = requests.get(f"https://apirest.wyscout.com/v3/matches/{5415673}/events", auth=(username, password))
event_data = pd.DataFrame(event_data.json()['events'])
event_data.head()

,id,matchId,matchPeriod,minute,second,matchTimestamp,videoTimestamp,relatedEventId,type,location,team,opponentTeam,player,pass,shot,groundDuel,aerialDuel,infraction,carry,possession
0,1480212789,5415673,1H,0,6,00:00:06.910,8.910437,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'x': 29, 'y': 38}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't..."
1,1480212788,5415673,1H,0,6,00:00:06.914,8.914118,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 50, 'y': 50}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't..."
2,1480212790,5415673,1H,0,9,00:00:09.085,11.085398,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 26, 'y': 70}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't..."
3,1480212791,5415673,1H,0,10,00:00:10.959,12.959132,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 29, 'y': 95}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't..."
4,1480212792,5415673,1H,0,13,00:00:13.055,15.055166,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 24, 'y': 77}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't..."

In [5]:
for index in np.arange(len(event_data)):
    row = event_data.iloc[index]
    if row['carry'] is not None:
        break
row['carry']

{'progression': 4.792, 'endLocation': {'x': 19, 'y': 63}}

## Remove Irrelevant Columns

In [6]:
event_data = event_data.drop(['minute', 'second','videoTimestamp'], axis=1)
event_data = event_data[event_data['matchPeriod'] != 'P']
event_data.head()

,id,matchId,matchPeriod,matchTimestamp,relatedEventId,type,location,team,opponentTeam,player,pass,shot,groundDuel,aerialDuel,infraction,carry,possession
0,1480212789,5415673,1H,00:00:06.910,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'x': 29, 'y': 38}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't..."
1,1480212788,5415673,1H,00:00:06.914,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 50, 'y': 50}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't..."
2,1480212790,5415673,1H,00:00:09.085,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 26, 'y': 70}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't..."
3,1480212791,5415673,1H,00:00:10.959,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 29, 'y': 95}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't..."
4,1480212792,5415673,1H,00:00:13.055,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 24, 'y': 77}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't..."

## Convert matchTimestamp to Seconds --> Add as Column

In [7]:
#Get time in seconds
match_time = []
for i in event_data['matchTimestamp'].tolist():
    time_list = i.split(':')
    seconds = float(time_list[0]) * 60 * 60
    seconds += float(time_list[1]) * 60
    seconds += float(time_list[2])
    match_time.append(seconds)
event_data['match_time_seconds'] = match_time
event_data = event_data.drop('matchTimestamp', axis=1)
event_data.head()

,id,matchId,matchPeriod,relatedEventId,type,location,team,opponentTeam,player,pass,shot,groundDuel,aerialDuel,infraction,carry,possession,match_time_seconds
0,1480212789,5415673,1H,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'x': 29, 'y': 38}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",6.910
1,1480212788,5415673,1H,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 50, 'y': 50}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",6.914
2,1480212790,5415673,1H,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 26, 'y': 70}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",9.085
3,1480212791,5415673,1H,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 29, 'y': 95}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",10.959
4,1480212792,5415673,1H,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 24, 'y': 77}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",13.055

## One Hot Encode Match Period

In [8]:
first_half = []
second_half = []
extra_time_1 = []
extra_time_2 = []
for i in event_data['matchPeriod'].tolist():
    if i == '1H':
        first_half.append(1)
        second_half.append(0)
        extra_time_1.append(0)
        extra_time_2.append(0)
    elif i == '2H':
        first_half.append(0)
        second_half.append(1)
        extra_time_1.append(0)
        extra_time_2.append(0)
    elif i == '1E':
        first_half.append(0)
        second_half.append(0)
        extra_time_1.append(1)
        extra_time_2.append(0)
    else:
        first_half.append(0)
        second_half.append(0)
        extra_time_1.append(0)
        extra_time_2.append(1)
event_data = event_data.drop('matchPeriod', axis=1)
event_data['1H'] = first_half
event_data['2H'] = second_half
event_data['1E'] = extra_time_1
event_data['2E'] = extra_time_2
event_data.head()

,id,matchId,relatedEventId,type,location,team,opponentTeam,player,pass,shot,groundDuel,aerialDuel,infraction,carry,possession,match_time_seconds,1H,2H,1E,2E
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'x': 29, 'y': 38}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",6.910,1,0,0,0
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 50, 'y': 50}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",6.914,1,0,0,0
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 26, 'y': 70}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",9.085,1,0,0,0
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 29, 'y': 95}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",10.959,1,0,0,0
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 24, 'y': 77}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",13.055,1,0,0,0

## Add Home Team Binary Vector

In [9]:
match_call = requests.get("https://apirest.wyscout.com/v3/matches/%s?useSides=1" % 5415673, auth=(username, password))
home_id = pd.DataFrame(match_call.json()['teamsData'])['home'].tolist()[0]
home_team = []
for i in event_data['team'].tolist():
    if i['id'] == home_id:
        home_team.append(1)
    else:
        home_team.append(0)
event_data['home_team'] = home_team
event_data.head()

,id,matchId,relatedEventId,type,location,team,opponentTeam,player,pass,shot,...,aerialDuel,infraction,carry,possession,match_time_seconds,1H,2H,1E,2E,home_team
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'x': 29, 'y': 38}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,...,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",6.910,1,0,0,0,0
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 50, 'y': 50}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,...,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",6.914,1,0,0,0,0
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 26, 'y': 70}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,...,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",9.085,1,0,0,0,0
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 29, 'y': 95}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,...,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",10.959,1,0,0,0,0
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 24, 'y': 77}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,...,None,None,None,"{'id': 1480212789, 'duration': '14.809237', 't...",13.055,1,0,0,0,0

## One Hot Encode Primary Action Type

In [10]:
primary_events = ['pass',
 'interception',
 'corner',
 'goalkeeper_exit',
 'shot',
 'goal_kick',
 'duel',
 'throw_in',
 'touch',
 'infraction',
 'free_kick',
 'clearance',
 'shot_against',
 'acceleration',
 'offside']
event_dict = {}
for i in primary_events:
    event_dict[i] = []
for i in event_data['type'].tolist():
    event = i['primary']
    for x in list(event_dict.keys()):
        if x == event:
            lista = event_dict[x]
            lista.append(1)
            event_dict[x] = lista
        else:
            lista = event_dict[x]
            lista.append(0)
            event_dict[x] = lista
for i in list(event_dict.keys()):
    event_data[i + '_primary_dummy'] = event_dict[i]
event_data.head()

,id,matchId,relatedEventId,type,location,team,opponentTeam,player,pass,shot,...,goal_kick_primary_dummy,duel_primary_dummy,throw_in_primary_dummy,touch_primary_dummy,infraction_primary_dummy,free_kick_primary_dummy,clearance_primary_dummy,shot_against_primary_dummy,acceleration_primary_dummy,offside_primary_dummy
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'x': 29, 'y': 38}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,...,0,0,0,0,0,0,0,0,0,0
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 50, 'y': 50}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,...,0,0,0,0,0,0,0,0,0,0
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 26, 'y': 70}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,...,0,0,0,0,0,0,0,0,0,0
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 29, 'y': 95}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,...,0,0,0,0,0,0,0,0,0,0
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 24, 'y': 77}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,...,0,0,0,0,0,0,0,0,0,0

## One Hot Encode Secondary Action Type

In [11]:
secondary_events = ['back_pass',
 'short_or_medium_pass',
 'lateral_pass',
 'linkup_play',
 'under_pressure',
 'forward_pass',
 'long_pass',
 'pass_to_final_third',
 'progressive_pass',
 'smart_pass',
 'through_pass',
 'cross',
 'loss',
 'pass_to_penalty_area',
 'cross_blocked',
 'recovery',
 'shot_after_corner',
 'loose_ball_duel',
 'pass',
 'counterpressing_recovery',
 'head_pass',
 'defensive_duel',
 'ground_duel',
 'dribble',
 'offensive_duel',
 'carry',
 'foul_suffered',
 'foul',
 'sliding_tackle',
 'touch_in_box',
 'deep_completion',
 'aerial_duel',
 'progressive_run',
 'dribbled_past_attempt',
 'free_kick_cross',
 'deep_completed_cross',
 'opportunity',
 'shot_assist',
 'save',
 'shot_after_throw_in',
 'shot_block',
 'hand_pass',
 'acceleration',
 'head_shot',
 'save_with_reflex',
 'interception',
 'red_card',
 'yellow_card',
 'key_pass',
'goal',
'conceded_goal',
'second_assist',
'assist',
'third_assist',
'shot_after_free_kick']
event_dict = {}
for i in secondary_events:
    event_dict[i] = []
for i in event_data['type'].tolist():
    event = i['secondary']
    if len(event) == 0:
        for x in list(event_dict.keys()):
            lista = event_dict[x]
            lista.append(0)
            event_dict[x] = lista
    else:
        for x in list(event_dict.keys()):
            if x in event:
                lista = event_dict[x]
                lista.append(1)
                event_dict[x] = lista
            else:
                lista = event_dict[x]
                lista.append(0)
                event_dict[x] = lista
for i in list(event_dict.keys()):
    event_data[i + '_secondary_dummy'] = event_dict[i]
event_data.head()

,id,matchId,relatedEventId,type,location,team,opponentTeam,player,pass,shot,...,interception_secondary_dummy,red_card_secondary_dummy,yellow_card_secondary_dummy,key_pass_secondary_dummy,goal_secondary_dummy,conceded_goal_secondary_dummy,second_assist_secondary_dummy,assist_secondary_dummy,third_assist_secondary_dummy,shot_after_free_kick_secondary_dummy
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'x': 29, 'y': 38}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,...,0,0,0,0,0,0,0,0,0,0
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 50, 'y': 50}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,...,0,0,0,0,0,0,0,0,0,0
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 26, 'y': 70}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,...,0,0,0,0,0,0,0,0,0,0
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 29, 'y': 95}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,...,0,0,0,0,0,0,0,0,0,0
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 24, 'y': 77}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,...,0,0,0,0,0,0,0,0,0,0

## One Hot Encode Body Part Used to Perform Action

In [12]:
foot = []
head = []
hand = []
for index, i in enumerate(event_data['head_pass_secondary_dummy'].tolist()):
    if i or event_data['head_shot_secondary_dummy'].tolist()[index]:
        head.append(1)
        foot.append(0)
        hand.append(0)
    elif (event_data['hand_pass_secondary_dummy'].tolist()[index]) or (event_data.iloc[index]['infraction'] != None and event_data.iloc[index]['infraction']['type'] == 'hand_foul'):
        hand.append(1)
        foot.append(0)
        head.append(0)
    else:
        foot.append(1)
        hand.append(0)
        head.append(0)
event_data = event_data.drop(['head_shot_secondary_dummy', 'head_pass_secondary_dummy', 'hand_pass_secondary_dummy'], axis=1)
event_data['head'] = head
event_data['foot'] = foot
event_data['hand'] = hand
event_data.head()

,id,matchId,relatedEventId,type,location,team,opponentTeam,player,pass,shot,...,key_pass_secondary_dummy,goal_secondary_dummy,conceded_goal_secondary_dummy,second_assist_secondary_dummy,assist_secondary_dummy,third_assist_secondary_dummy,shot_after_free_kick_secondary_dummy,head,foot,hand
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'x': 29, 'y': 38}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,...,0,0,0,0,0,0,0,0,1,0
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 50, 'y': 50}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,...,0,0,0,0,0,0,0,0,1,0
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 26, 'y': 70}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,...,0,0,0,0,0,0,0,0,1,0
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'x': 29, 'y': 95}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,...,0,0,0,0,0,0,0,0,1,0
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 24, 'y': 77}","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,...,0,0,0,0,0,0,0,0,1,0

## Get Action Start and End x,y Coordinates

In [13]:
end_x = []
end_y = []
start_x = []
start_y = []
field_length = 100
field_width = 100
for i in np.arange(len(event_data)):
    row = event_data.iloc[i]
    locs = row['location'] 
    if locs != None:
        start_x.append(locs['x'])
        start_y.append(locs['y'])
    else:
        start_x.append('x')
        start_y.append('y')
        end_x.append('x')
        end_y.append('y')
        continue
    if row['player']['id'] == 0:
        end_x.append('x')
        end_y.append('y')
    elif row['pass'] != None:
        locs = row['pass']['endLocation']
        end_x.append(locs['x'])
        end_y.append(locs['y'])
    elif row['shot'] != None:
        locs = row['possession']
        if locs['eventsNumber'] == locs['eventIndex'] + 1:
            locs = locs['endLocation']
            end_x.append(locs['x'])
            end_y.append(locs['y'])
        else:
            print('ERROR')
    elif row['carry'] != None:
        locs = row['carry']['endLocation']
        end_x.append(locs['x'])
        end_y.append(locs['y'])
    else:
        locs = row['location']
        end_x.append(locs['x'])
        end_y.append(locs['y'])
event_data['end_x'] = end_x
event_data['end_y'] = end_y
event_data['start_x'] = start_x
event_data['start_y'] = start_y
event_data = event_data.drop('location', axis=1)
event_data = event_data[event_data['start_x'] != 'x']
event_data = event_data[event_data['end_x'] != 'x']
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,assist_secondary_dummy,third_assist_secondary_dummy,shot_after_free_kick_secondary_dummy,head,foot,hand,end_x,end_y,start_x,start_y
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,0,0,1,0,50,50,29,38
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,0,0,1,0,26,70,50,50
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,0,0,1,0,29,95,26,70
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,0,0,1,0,24,77,29,95
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,0,0,1,0,10,59,24,77

## Euclidean Distances

In [14]:
def euclideanDistance(start_x, start_y, end_x, end_y):
    return ((start_x - end_x)**2 + (start_y - end_y)**2)**0.5

### Calculate Euclidean Distance Between Action Start and End Location

In [15]:
start_end_distance = []
for index, i in enumerate(event_data['start_x'].tolist()):
    start_x = i
    start_y = event_data['start_y'].tolist()[index]
    end_x = event_data['end_x'].tolist()[index]
    end_y = event_data['end_y'].tolist()[index]
    euclidean_distance = euclideanDistance(start_x, start_y, end_x, end_y)
    start_end_distance.append(euclidean_distance)
event_data['start_end_distance'] = start_end_distance
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,third_assist_secondary_dummy,shot_after_free_kick_secondary_dummy,head,foot,hand,end_x,end_y,start_x,start_y,start_end_distance
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,0,1,0,50,50,29,38,24.186773
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,0,1,0,26,70,50,50,31.240999
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,0,1,0,29,95,26,70,25.179357
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,0,1,0,24,77,29,95,18.681542
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,0,1,0,10,59,24,77,22.803509

### Calculate Euclidean Distance Between Action Start and Opponent Goal

In [16]:
start_goal_distance = []
for index, i in enumerate(event_data['start_x'].tolist()):
    start_x = i
    start_y = event_data['start_y'].tolist()[index]
    end_x = 100
    end_y = 50
    euclidean_distance = euclideanDistance(start_x, start_y, end_x, end_y)
    start_goal_distance.append(euclidean_distance)
event_data['start_goal_distance_opponent'] = start_goal_distance
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,shot_after_free_kick_secondary_dummy,head,foot,hand,end_x,end_y,start_x,start_y,start_end_distance,start_goal_distance_opponent
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,1,0,50,50,29,38,24.186773,72.006944
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,1,0,26,70,50,50,31.240999,50.000000
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,1,0,29,95,26,70,25.179357,76.655072
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,1,0,24,77,29,95,18.681542,84.059503
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,1,0,10,59,24,77,22.803509,80.653580

### Calculate Euclidean Distance Between Action Start and Own Goal

In [17]:
start_goal_distance = []
for index, i in enumerate(event_data['start_x'].tolist()):
    start_x = i
    start_y = event_data['start_y'].tolist()[index]
    end_x = 0
    end_y = 50
    euclidean_distance = euclideanDistance(start_x, start_y, end_x, end_y)
    start_goal_distance.append(euclidean_distance)
event_data['start_goal_distance_own'] = start_goal_distance
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,head,foot,hand,end_x,end_y,start_x,start_y,start_end_distance,start_goal_distance_opponent,start_goal_distance_own
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,1,0,50,50,29,38,24.186773,72.006944,31.384710
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,1,0,26,70,50,50,31.240999,50.000000,50.000000
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,1,0,29,95,26,70,25.179357,76.655072,32.802439
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,1,0,24,77,29,95,18.681542,84.059503,53.535035
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,1,0,10,59,24,77,22.803509,80.653580,36.124784

### Calculate Euclidean Distance Between Action End and Opponent Goal

In [18]:
start_goal_distance = []
for index, i in enumerate(event_data['end_x'].tolist()):
    start_x = i
    start_y = event_data['end_y'].tolist()[index]
    end_x = 100
    end_y = 50
    euclidean_distance = euclideanDistance(start_x, start_y, end_x, end_y)
    start_goal_distance.append(euclidean_distance)
event_data['end_goal_distance_opponent'] = start_goal_distance
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,foot,hand,end_x,end_y,start_x,start_y,start_end_distance,start_goal_distance_opponent,start_goal_distance_own,end_goal_distance_opponent
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,1,0,50,50,29,38,24.186773,72.006944,31.384710,50.000000
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,1,0,26,70,50,50,31.240999,50.000000,50.000000,76.655072
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,1,0,29,95,26,70,25.179357,76.655072,32.802439,84.059503
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,1,0,24,77,29,95,18.681542,84.059503,53.535035,80.653580
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,1,0,10,59,24,77,22.803509,80.653580,36.124784,90.448881

### Calculate Euclidean Distance Between Action End and Own Goal

In [19]:
start_goal_distance = []
for index, i in enumerate(event_data['end_x'].tolist()):
    start_x = i
    start_y = event_data['end_y'].tolist()[index]
    end_x = 0
    end_y = 50
    euclidean_distance = euclideanDistance(start_x, start_y, end_x, end_y)
    start_goal_distance.append(euclidean_distance)
event_data['end_goal_distance_own'] = start_goal_distance
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,hand,end_x,end_y,start_x,start_y,start_end_distance,start_goal_distance_opponent,start_goal_distance_own,end_goal_distance_opponent,end_goal_distance_own
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,50,50,29,38,24.186773,72.006944,31.384710,50.000000,50.000000
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,26,70,50,50,31.240999,50.000000,50.000000,76.655072,32.802439
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,29,95,26,70,25.179357,76.655072,32.802439,84.059503,53.535035
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,24,77,29,95,18.681542,84.059503,53.535035,80.653580,36.124784
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,10,59,24,77,22.803509,80.653580,36.124784,90.448881,13.453624

## Calculate Number of Goals Each Team Has Scored and Goal Differential

In [20]:
home_goals = []
away_goals = []
delta = []
hg = 0
ag = 0
for index,i in enumerate(event_data['type'].tolist()):
    if 'goal' in i['secondary']:
        if event_data['home_team'].tolist()[index]:
            hg += 1
        else:
            ag += 1
    home_goals.append(hg)
    away_goals.append(ag)
    delta.append(hg-ag)
event_data['home_goals'] = home_goals
event_data['away_goals'] = away_goals
event_data['goal_delta'] = delta
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,start_x,start_y,start_end_distance,start_goal_distance_opponent,start_goal_distance_own,end_goal_distance_opponent,end_goal_distance_own,home_goals,away_goals,goal_delta
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,29,38,24.186773,72.006944,31.384710,50.000000,50.000000,0,0,0
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,50,50,31.240999,50.000000,50.000000,76.655072,32.802439,0,0,0
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,26,70,25.179357,76.655072,32.802439,84.059503,53.535035,0,0,0
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,29,95,18.681542,84.059503,53.535035,80.653580,36.124784,0,0,0
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,24,77,22.803509,80.653580,36.124784,90.448881,13.453624,0,0,0

## Calculate Number of Red Cards Each Team Has and Red Card Differential

In [21]:
home_reds = []
away_reds = []
delta = []
hr = 0
ar = 0
for index,i in enumerate(event_data['type'].tolist()):
    if 'red_card' in i['secondary']:
        if event_data['home_team'].tolist()[index]:
            hr += 1
        else:
            ar += 1
    home_reds.append(hr)
    away_reds.append(ar)
    delta.append(hr-ar)
event_data['home_red_cards'] = home_reds
event_data['away_red_cards'] = away_reds
event_data['red_card_delta'] = delta
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,start_goal_distance_opponent,start_goal_distance_own,end_goal_distance_opponent,end_goal_distance_own,home_goals,away_goals,goal_delta,home_red_cards,away_red_cards,red_card_delta
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,72.006944,31.384710,50.000000,50.000000,0,0,0,0,0,0
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,50.000000,50.000000,76.655072,32.802439,0,0,0,0,0,0
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,76.655072,32.802439,84.059503,53.535035,0,0,0,0,0,0
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,84.059503,53.535035,80.653580,36.124784,0,0,0,0,0,0
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,80.653580,36.124784,90.448881,13.453624,0,0,0,0,0,0

## Calculate Number of Yellow Cards Each Team Has and Yellow Card Differential

In [22]:
home_yellows = []
away_yellows = []
delta = []
hy = 0
ay = 0
for index,i in enumerate(event_data['type'].tolist()):
    if 'yellow_card' in i['secondary']:
        if event_data['home_team'].tolist()[index]:
            hy += 1
        else:
            ay += 1
    home_yellows.append(hy)
    away_yellows.append(ay)
    delta.append(hy-ay)
event_data['home_yellow_cards'] = home_yellows
event_data['away_yellow_cards'] = away_yellows
event_data['yellow_card_delta'] = delta
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,end_goal_distance_own,home_goals,away_goals,goal_delta,home_red_cards,away_red_cards,red_card_delta,home_yellow_cards,away_yellow_cards,yellow_card_delta
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,50.000000,0,0,0,0,0,0,0,0,0
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,32.802439,0,0,0,0,0,0,0,0,0
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,53.535035,0,0,0,0,0,0,0,0,0
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,36.124784,0,0,0,0,0,0,0,0,0
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,13.453624,0,0,0,0,0,0,0,0,0

## Calculate Possession Event Index

In [23]:
event_indices = []
for i in event_data['possession'].tolist():
    if i != None:
        event_indices.append(i['eventIndex'] + 1)
    else:
        event_indices.append(0)
event_data['possession_event_index'] = event_indices
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,home_goals,away_goals,goal_delta,home_red_cards,away_red_cards,red_card_delta,home_yellow_cards,away_yellow_cards,yellow_card_delta,possession_event_index
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,0,0,0,0,0,0,0,1
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,0,0,0,0,0,0,0,2
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,0,0,0,0,0,0,0,3
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,0,0,0,0,0,0,0,4
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,0,0,0,0,0,0,0,5

## One Hot Encode Action Height

In [24]:
high = []
nan = []
low = []
blocked = []
for i in np.arange(len(event_data)):
    row = event_data.iloc[i]
    if row['pass'] != None:
        height = row['pass']['height']
        if height == 'high':
            high.append(1)
            nan.append(0)
            low.append(0)
            blocked.append(0)
        elif height == 'low':
            high.append(0)
            nan.append(0)
            low.append(1)
            blocked.append(0)
        elif height == 'blocked':
            high.append(0)
            nan.append(0)
            low.append(0)
            blocked.append(1)
        else:
            high.append(0)
            nan.append(1)
            low.append(0)
            blocked.append(0)
    else:
        high.append(0)
        nan.append(1)
        low.append(0)
        blocked.append(0)
event_data['action_height_high'] = high
event_data['action_height_low'] = low
event_data['action_height_blocked'] = blocked
event_data['action_height_nan'] = nan
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,away_red_cards,red_card_delta,home_yellow_cards,away_yellow_cards,yellow_card_delta,possession_event_index,action_height_high,action_height_low,action_height_blocked,action_height_nan
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,0,0,0,1,0,0,0,1
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,0,0,0,2,0,0,0,1
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,0,0,0,3,0,0,0,1
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,0,0,0,4,0,0,0,1
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,0,0,0,5,0,0,0,1

## Calculate Angles

In [25]:
def calc_angle(start_x, start_y, end_x, end_y):
    start_coord = [start_x, start_y]
    end_coord = [end_x, end_y]
    stand_field_length = 1.05
    stand_field_width = 0.68
    # use coor variables to calculate angle between action vector and true forward
    # use goal variables to calculate angle between action vector and vector from action start to the opponent's goal
    x_coor = 100
    y_coor = start_y
    forward_coord = [x_coor, y_coor]

    x_goal = 100
    y_goal = 50

    vec_1 = np.subtract(forward_coord, start_coord)
    vec_2 = np.subtract(end_coord, start_coord)
    
    vec_1[0] = vec_1[0]*stand_field_length
    vec_1[1] = vec_1[1]*stand_field_width
    vec_2[0] = vec_2[0]*stand_field_length
    vec_2[1] = vec_2[1]*stand_field_width

    if np.array_equal(vec_1, [0,0]) or np.array_equal(vec_2, [0,0]):
        angle = 0

    else:
        angle = np.degrees(np.arccos(np.dot(vec_1, vec_2) / (np.sqrt(sum(i**2 for i in vec_1)) * np.sqrt(sum(i**2 for i in vec_2)))))

    if vec_1[0]*vec_2[1] - vec_1[1]*vec_2[0] < 0:
        angle = -angle
        
    return angle

### Angle Between Start and End Location

In [26]:
start_end_angle= []
for index, i in enumerate(event_data['start_x'].tolist()):
    start_x = i
    start_y = event_data['start_y'].tolist()[index]
    end_x = event_data['end_x'].tolist()[index]
    end_y = event_data['end_y'].tolist()[index]
    angle = calc_angle(start_x, start_y, end_x, end_y)
    start_end_angle.append(angle)
event_data['start_end_angle'] = start_end_angle
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,red_card_delta,home_yellow_cards,away_yellow_cards,yellow_card_delta,possession_event_index,action_height_high,action_height_low,action_height_blocked,action_height_nan,start_end_angle
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,0,0,1,0,0,0,1,19.983107
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,0,0,2,0,0,0,1,152.525568
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,0,0,3,0,0,0,1,79.992020
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,0,0,4,0,0,0,1,-112.619865
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,0,0,5,0,0,0,1,-139.398705

### Angle Between Start and Opponent Goal

In [27]:
start_end_angle= []
for index, i in enumerate(event_data['start_x'].tolist()):
    start_x = i
    start_y = event_data['start_y'].tolist()[index]
    end_x = 100
    end_y = 50
    angle = calc_angle(start_x, start_y, end_x, end_y)
    start_end_angle.append(angle)
event_data['start_goal_angle_opponent'] = start_end_angle
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,home_yellow_cards,away_yellow_cards,yellow_card_delta,possession_event_index,action_height_high,action_height_low,action_height_blocked,action_height_nan,start_end_angle,start_goal_angle_opponent
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,0,1,0,0,0,1,19.983107,6.170175
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,0,2,0,0,0,1,152.525568,0.000000
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,0,3,0,0,0,1,79.992020,-9.582945
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,0,4,0,0,0,1,-112.619865,-22.067900
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,0,5,0,0,0,1,-139.398705,-12.835609

### Angle Between Start and Own Goal

In [28]:
start_end_angle= []
for index, i in enumerate(event_data['start_x'].tolist()):
    start_x = i
    start_y = event_data['start_y'].tolist()[index]
    end_x = 0
    end_y = 50
    angle = calc_angle(start_x, start_y, end_x, end_y)
    start_end_angle.append(angle)
event_data['start_goal_angle_own'] = start_end_angle
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,away_yellow_cards,yellow_card_delta,possession_event_index,action_height_high,action_height_low,action_height_blocked,action_height_nan,start_end_angle,start_goal_angle_opponent,start_goal_angle_own
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,1,0,0,0,1,19.983107,6.170175,165.068583
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,2,0,0,0,1,152.525568,0.000000,180.000000
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,3,0,0,0,1,79.992020,-9.582945,-154.290046
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,4,0,0,0,1,-112.619865,-22.067900,-135.000000
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,5,0,0,0,1,-139.398705,-12.835609,-144.246113

### Angle Between End and Opponent Goal

In [29]:
start_end_angle= []
for index, i in enumerate(event_data['end_x'].tolist()):
    start_x = i
    start_y = event_data['end_y'].tolist()[index]
    end_x = 100
    end_y = 50
    angle = calc_angle(start_x, start_y, end_x, end_y)
    start_end_angle.append(angle)
event_data['end_goal_angle_opponent'] = start_end_angle
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,yellow_card_delta,possession_event_index,action_height_high,action_height_low,action_height_blocked,action_height_nan,start_end_angle,start_goal_angle_opponent,start_goal_angle_own,end_goal_angle_opponent
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,1,0,0,0,1,19.983107,6.170175,165.068583,0.000000
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,2,0,0,0,1,152.525568,0.000000,180.000000,-9.582945
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,3,0,0,0,1,79.992020,-9.582945,-154.290046,-22.067900
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,4,0,0,0,1,-112.619865,-22.067900,-135.000000,-12.835609
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,5,0,0,0,1,-139.398705,-12.835609,-144.246113,-3.652223

### Angle Between End and Own Goal

In [30]:
start_end_angle= []
for index, i in enumerate(event_data['end_x'].tolist()):
    start_x = i
    start_y = event_data['end_y'].tolist()[index]
    end_x = 0
    end_y = 50
    angle = calc_angle(start_x, start_y, end_x, end_y)
    start_end_angle.append(angle)
event_data['end_goal_angle_own'] = start_end_angle
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,possession_event_index,action_height_high,action_height_low,action_height_blocked,action_height_nan,start_end_angle,start_goal_angle_opponent,start_goal_angle_own,end_goal_angle_opponent,end_goal_angle_own
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,1,0,0,0,1,19.983107,6.170175,165.068583,0.000000,180.000000
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,2,0,0,0,1,152.525568,0.000000,180.000000,-9.582945,-154.290046
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,3,0,0,0,1,79.992020,-9.582945,-154.290046,-22.067900,-135.000000
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,4,0,0,0,1,-112.619865,-22.067900,-135.000000,-12.835609,-144.246113
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,5,0,0,0,1,-139.398705,-12.835609,-144.246113,-3.652223,-149.036243

## Extract Useful Info From Each Subevent

### Passes

In [31]:
success = []
missing = []
for i in np.arange(len(event_data)):
    row = event_data.iloc[i]
    if row['pass'] != None:
        missing.append(0)
        if row['pass']['accurate']:
            success.append(1)
        else:
            success.append(0)
    else:
        success.append(0)
        missing.append(1)
event_data['accurate_pass'] = success
event_data['not_pass_event'] = missing
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,action_height_low,action_height_blocked,action_height_nan,start_end_angle,start_goal_angle_opponent,start_goal_angle_own,end_goal_angle_opponent,end_goal_angle_own,accurate_pass,not_pass_event
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,1,19.983107,6.170175,165.068583,0.000000,180.000000,1,0
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,1,152.525568,0.000000,180.000000,-9.582945,-154.290046,1,0
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,1,79.992020,-9.582945,-154.290046,-22.067900,-135.000000,1,0
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,1,-112.619865,-22.067900,-135.000000,-12.835609,-144.246113,1,0
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,1,-139.398705,-12.835609,-144.246113,-3.652223,-149.036243,1,0

### Shots

In [32]:
on_target = []
goal = []
missing = []
for i in np.arange(len(event_data)):
    row = event_data.iloc[i]
    if row['shot'] != None:
        missing.append(0)
        if row['shot']['onTarget']:
            on_target.append(1)
        else:
            on_target.append(0)
        if row['shot']['isGoal']:
            goal.append(1)
        else:
            goal.append(0)
    else:
        on_target.append(0)
        goal.append(0)
        missing.append(1)
event_data['shot_on_target'] = on_target
event_data['shot_goal'] = goal
event_data['not_shot_event'] = missing
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,start_end_angle,start_goal_angle_opponent,start_goal_angle_own,end_goal_angle_opponent,end_goal_angle_own,accurate_pass,not_pass_event,shot_on_target,shot_goal,not_shot_event
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,19.983107,6.170175,165.068583,0.000000,180.000000,1,0,0,0,1
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,152.525568,0.000000,180.000000,-9.582945,-154.290046,1,0,0,0,1
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,79.992020,-9.582945,-154.290046,-22.067900,-135.000000,1,0,0,0,1
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,-112.619865,-22.067900,-135.000000,-12.835609,-144.246113,1,0,0,0,1
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,-139.398705,-12.835609,-144.246113,-3.652223,-149.036243,1,0,0,0,1

### Ground Duels

In [40]:
missing_off = []
kept_possession = []
progressed_with_ball = []

missing_def = []
stopped_progress = []
recovered_possession = []

takeon = []
for i in np.arange(len(event_data)):
    row = event_data.iloc[i]
    if row['groundDuel'] != None:
        if row['groundDuel']['takeOn']:
            takeon.append(1)
        else:
            takeon.append(0)
        if row['groundDuel']['duelType'] == 'defensive_duel':
            missing_def.append(0)
            missing_off.append(1)
            kept_possession.append(0)
            progressed_with_ball.append(0)
            if row['groundDuel']['stoppedProgress']:
                stopped_progress.append(1)
            else:
                stopped_progress.append(0)
            if row['groundDuel']['recoveredPossession']:
                recovered_possession.append(1)
            else:
                recovered_possession.append(0) 
        elif row['groundDuel']['duelType'] == 'offensive_duel' or row['groundDuel']['duelType'] == 'dribble':
            missing_def.append(1)
            missing_off.append(0)
            stopped_progress.append(0)
            recovered_possession.append(0)
            if row['groundDuel']['keptPossession']:
                kept_possession.append(1)
            else:
                kept_possession.append(0)
            if row['groundDuel']['progressedWithBall']:
                progressed_with_ball.append(1)
            else:
                progressed_with_ball.append(0)
        else:
            print(row['groundDuel'])
    else:
        missing_off.append(1)
        missing_def.append(1)
        kept_possession.append(0)
        progressed_with_ball.append(0)
        stopped_progress.append(0)
        recovered_possession.append(0)
        takeon.append(0)
event_data['take_on'] = takeon
event_data['kept_possession_duel'] = kept_possession
event_data['progressed_with_ball_duel'] = progressed_with_ball
event_data['stopped_progress_duel'] = stopped_progress
event_data['recovered_possession_duel'] = recovered_possession
event_data['not_defensive_duel'] = missing_def
event_data['not_offensive_duel'] = missing_off
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,shot_on_target,shot_goal,not_shot_event,take_on,kept_possession_duel,progressed_with_ball_duel,stopped_progress_duel,recovered_possession_duel,not_defensive_duel,not_offensive_duel
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,1,0,0,0,0,0,1,1
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,1,0,0,0,0,0,1,1
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,1,0,0,0,0,0,1,1
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,1,0,0,0,0,0,1,1
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,1,0,0,0,0,0,1,1

### Aerial Duels

In [41]:
first_touch = []
missing = []
height = []
for i in np.arange(len(event_data)):
    row = event_data.iloc[i]
    if row['aerialDuel'] != None:
        missing.append(0)
        if row['aerialDuel']['firstTouch']:
            first_touch.append(1)
        else:
            first_touch.append(0)
        height.append(row['aerialDuel']['height'])
    else:
        missing.append(1)
        first_touch.append(0)
        height.append(0)
event_data['first_touch_aerial_duel'] = first_touch
event_data['aerial_duel_height'] = height
event_data['not_aerial_duel'] = missing
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,take_on,kept_possession_duel,progressed_with_ball_duel,stopped_progress_duel,recovered_possession_duel,not_defensive_duel,not_offensive_duel,first_touch_aerial_duel,aerial_duel_height,not_aerial_duel
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,0,0,0,1,1,0,0,1
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,0,0,0,1,1,0,0,1
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,0,0,0,1,1,0,0,1
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,0,0,0,1,1,0,0,1
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,0,0,0,1,1,0,0,1

### Infractions

In [42]:
red = []
yellow = []
missing = []
for i in np.arange(len(event_data)):
    row = event_data.iloc[i]
    if row['infraction'] != None:
        missing.append(0)
        if row['infraction']['yellowCard']:
            yellow.append(1)
        else:
            yellow.append(0)
        if row['infraction']['redCard']:
            red.append(1)
        else:
            red.append(0)
    else:
        missing.append(1)
        yellow.append(0)
        red.append(0)
event_data['yellow_card_infraction'] = yellow
event_data['red_card_infraction'] = red
event_data['not_infraction'] = missing
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,stopped_progress_duel,recovered_possession_duel,not_defensive_duel,not_offensive_duel,first_touch_aerial_duel,aerial_duel_height,not_aerial_duel,yellow_card_infraction,red_card_infraction,not_infraction
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,0,1,1,0,0,1,0,0,1
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,0,1,1,0,0,1,0,0,1
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,0,1,1,0,0,1,0,0,1
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,0,1,1,0,0,1,0,0,1
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,0,1,1,0,0,1,0,0,1

### Carries

In [43]:
prog = []
missing = []
for i in np.arange(len(event_data)):
    row = event_data.iloc[i]
    if row['carry'] != None:
        missing.append(0)
        prog.append(row['carry']['progression'])
    else:
        missing.append(1)
        prog.append(0)
event_data['progression_carry'] = prog
event_data['not_carry'] = missing
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,not_defensive_duel,not_offensive_duel,first_touch_aerial_duel,aerial_duel_height,not_aerial_duel,yellow_card_infraction,red_card_infraction,not_infraction,progression_carry,not_carry
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,1,1,0,0,1,0,0,1,0.0,1
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,1,1,0,0,1,0,0,1,0.0,1
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,1,1,0,0,1,0,0,1,0.0,1
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,1,1,0,0,1,0,0,1,0.0,1
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,1,1,0,0,1,0,0,1,0.0,1

### Possession

In [44]:
missing = []
trans_low = []
trans_med = []
trans_high = []
attack = []
counter = []
for i in np.arange(len(event_data)):
    row = event_data.iloc[i]
    if row['possession'] != None:
        missing.append(0)
        if row['possession']['types'] == 'transition_low':
            trans_high.append(0)
            trans_low.append(1)
            trans_med.append(0)
            attack.append(0)
            counter.append(0)
        elif row['possession']['types'] == 'transition_medium':
            trans_high.append(0)
            trans_low.append(0)
            trans_med.append(1)
            attack.append(0)
            counter.append(0)
        elif row['possession']['types'] == 'transition_high':
            trans_high.append(1)
            trans_low.append(0)
            trans_med.append(0)
            attack.append(0)
            counter.append(0)
        elif row['possession']['types'] == 'attack':
            trans_high.append(0)
            trans_low.append(0)
            trans_med.append(0)
            attack.append(1)
            counter.append(0)
        elif row['possession']['types'] == 'counterattack':
            trans_high.append(0)
            trans_low.append(0)
            trans_med.append(0)
            attack.append(0)
            counter.append(1)
        else:
            trans_high.append(0)
            trans_low.append(0)
            trans_med.append(0)
            attack.append(0)
            counter.append(0)
    else:
        missing.append(1)
        trans_high.append(0)
        trans_low.append(0)
        trans_med.append(0)
        attack.append(0)
        counter.append(0)
event_data['not_possession'] = missing
event_data['trans_high_possession'] = trans_high
event_data['trans_med_possession'] = trans_med
event_data['trans_low_possession'] = trans_low
event_data['attack_possession'] = attack
event_data['counterattack_possession'] = counter
event_data.head()

,id,matchId,relatedEventId,type,team,opponentTeam,player,pass,shot,groundDuel,...,red_card_infraction,not_infraction,progression_carry,not_carry,not_possession,trans_high_possession,trans_med_possession,trans_low_possession,attack_possession,counterattack_possession
0,1480212789,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684870, 'name': 'K. Groff', 'position':...","{'accurate': True, 'angle': 19, 'height': None...",None,None,...,0,1,0.0,1,0,0,0,0,0,0
1,1480212788,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 655938, 'name': 'M. Cooper', 'position'...","{'accurate': True, 'angle': 152, 'height': Non...",None,None,...,0,1,0.0,1,0,0,0,0,0,0
2,1480212790,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': 80, 'height': None...",None,None,...,0,1,0.0,1,0,0,0,0,0,0
3,1480212791,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['lateral_pas...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 684871, 'name': 'D. Graham', 'position'...","{'accurate': True, 'angle': -111, 'height': No...",None,None,...,0,1,0.0,1,0,0,0,0,0,0
4,1480212792,5415673,1.480213e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'id': 61485, 'name': 'Duke Blue Devils', 'for...","{'id': 61772, 'name': 'Alabama Crimson Tide', ...","{'id': 668789, 'name': 'J. Royson', 'position'...","{'accurate': True, 'angle': -139, 'height': No...",None,None,...,0,1,0.0,1,0,0,0,0,0,0

# Iterate Through all Matches

In [47]:
event_data.columns[0:100]

Index(['id', 'matchId', 'relatedEventId', 'type', 'team', 'opponentTeam',
       'player', 'pass', 'shot', 'groundDuel', 'aerialDuel', 'infraction',
       'carry', 'possession', 'match_time_seconds', '1H', '2H', '1E', '2E',
       'home_team', 'pass_primary_dummy', 'interception_primary_dummy',
       'corner_primary_dummy', 'goalkeeper_exit_primary_dummy',
       'shot_primary_dummy', 'goal_kick_primary_dummy', 'duel_primary_dummy',
       'throw_in_primary_dummy', 'touch_primary_dummy',
       'infraction_primary_dummy', 'free_kick_primary_dummy',
       'clearance_primary_dummy', 'shot_against_primary_dummy',
       'acceleration_primary_dummy', 'offside_primary_dummy',
       'back_pass_secondary_dummy', 'short_or_medium_pass_secondary_dummy',
       'lateral_pass_secondary_dummy', 'linkup_play_secondary_dummy',
       'under_pressure_secondary_dummy', 'forward_pass_secondary_dummy',
       'long_pass_secondary_dummy', 'pass_to_final_third_secondary_dummy',
       'progressive_pass_secondary_dummy', 'smart_pass_secondary_dummy',
       'through_pass_secondary_dummy', 'cross_secondary_dummy',
       'loss_secondary_dummy', 'pass_to_penalty_area_secondary_dummy',
       'cross_blocked_secondary_dummy', 'recovery_secondary_dummy',
       'shot_after_corner_secondary_dummy', 'loose_ball_duel_secondary_dummy',
       'pass_secondary_dummy', 'counterpressing_recovery_secondary_dummy',
       'defensive_duel_secondary_dummy', 'ground_duel_secondary_dummy',
       'dribble_secondary_dummy', 'offensive_duel_secondary_dummy',
       'carry_secondary_dummy', 'foul_suffered_secondary_dummy',
       'foul_secondary_dummy', 'sliding_tackle_secondary_dummy',
       'touch_in_box_secondary_dummy', 'deep_completion_secondary_dummy',
       'aerial_duel_secondary_dummy', 'progressive_run_secondary_dummy',
       'dribbled_past_attempt_secondary_dummy',
       'free_kick_cross_secondary_dummy',
       'deep_completed_cross_secondary_dummy', 'opportunity_secondary_dummy',
       'shot_assist_secondary_dummy', 'save_secondary_dummy',
       'shot_after_throw_in_secondary_dummy', 'shot_block_secondary_dummy',
       'acceleration_secondary_dummy', 'save_with_reflex_secondary_dummy',
       'interception_secondary_dummy', 'red_card_secondary_dummy',
       'yellow_card_secondary_dummy', 'key_pass_secondary_dummy',
       'goal_secondary_dummy', 'conceded_goal_secondary_dummy',
       'second_assist_secondary_dummy', 'assist_secondary_dummy',
       'third_assist_secondary_dummy', 'shot_after_free_kick_secondary_dummy',
       'head', 'foot', 'hand', 'end_x', 'end_y', 'start_x', 'start_y',
       'start_end_distance', 'start_goal_distance_opponent',
       'start_goal_distance_own', 'end_goal_distance_opponent',
       'end_goal_distance_own', 'home_goals'],
      dtype='object')

In [42]:
#CODE THAT APPENDS EVENT DATA INTO A BIG DF
big_event_data = pd.DataFrame()
j = 1
for i in tqdm(matches_df['matchId'].tolist()):
    event_data = requests.get(f"https://apirest.wyscout.com/v3/matches/{i}/events", auth=(username, password))
    try:
        data = pd.DataFrame(event_data.json()['events'])
    except:
        print(f"Error {j}")
        j = j + 1
        continue
    big_event_data = pd.concat([big_event_data, data])

  0%|          | 0/5314 [00:00<?, ?it/s]
  0%|          | 1/5314 [00:04<6:25:25,  4.35s/it]

Error 1

  0%|          | 2/5314 [00:04<4:41:49,  3.18s/it]
  0%|          | 3/5314 [00:06<4:14:35,  2.88s/it]
  0%|          | 4/5314 [00:09<3:56:26,  2.67s/it]
  0%|          | 5/5314 [00:12<4:19:58,  2.94s/it]
  0%|          | 6/5314 [00:15<4:09:59,  2.83s/it]
  0%|          | 7/5314 [00:17<3:52:14,  2.63s/it]

Error 2

  0%|          | 8/5314 [00:18<3:02:31,  2.06s/it]

Error 3

  0%|          | 9/5314 [00:18<2:24:14,  1.63s/it]

Error 4

  0%|          | 10/5314 [00:19<1:54:37,  1.30s/it]
  0%|          | 11/5314 [00:21<2:16:34,  1.55s/it]
  0%|          | 12/5314 [00:24<2:43:13,  1.85s/it]

Error 5

  0%|          | 13/5314 [00:25<2:22:51,  1.62s/it]
  0%|          | 14/5314 [00:28<3:20:09,  2.27s/it]
  0%|          | 15/5314 [00:32<3:50:02,  2.60s/it]

Error 6

  0%|          | 16/5314 [00:32<2:55:52,  1.99s/it]
  0%|          | 17/5314 [00:35<3:19:50,  2.26s/it]
  0%|          | 18/5314 [00:37<3:17:22,  2.24s/it]
  0%|          | 19/5314 [00:41<3:57:09,  2.69s/it]
  0%|          | 20/5314 [00:45<4:22:08,  2.97s/it]
  0%|          | 21/5314 [00:48<4:29:41,  3.06s/it]
  0%|          | 22/5314 [00:51<4:27:22,  3.03s/it]

Error 7

  0%|          | 23/5314 [00:52<3:20:59,  2.28s/it]
  0%|          | 24/5314 [01:00<5:57:46,  4.06s/it]
  0%|          | 25/5314 [01:02<5:12:58,  3.55s/it]
  0%|          | 26/5314 [01:08<6:23:09,  4.35s/it]
  1%|          | 27/5314 [01:11<5:34:13,  3.79s/it]
  1%|          | 28/5314 [01:15<5:34:41,  3.80s/it]
  1%|          | 29/5314 [01:17<5:06:16,  3.48s/it]
  1%|          | 30/5314 [01:20<4:34:45,  3.12s/it]
  1%|          | 31/5314 [01:22<4:16:43,  2.92s/it]

Error 8

  1%|          | 32/5314 [01:23<3:11:49,  2.18s/it]
  1%|          | 33/5314 [01:25<3:06:52,  2.12s/it]
  1%|          | 34/5314 [01:30<4:33:42,  3.11s/it]
  1%|          | 35/5314 [01:32<4:08:23,  2.82s/it]
  1%|          | 36/5314 [01:35<3:59:26,  2.72s/it]
  1%|          | 37/5314 [01:38<4:20:47,  2.97s/it]
  1%|          | 38/5314 [01:43<5:10:15,  3.53s/it]
  1%|          | 39/5314 [01:45<4:36:34,  3.15s/it]
  1%|          | 40/5314 [01:50<5:18:07,  3.62s/it]
  1%|          | 41/5314 [01:52<4:43:08,  3.22s/it]
  1%|          | 42/5314 [01:58<5:55:31,  4.05s/it]
  1%|          | 43/5314 [02:02<5:58:20,  4.08s/it]
  1%|          | 44/5314 [02:09<6:54:40,  4.72s/it]
  1%|          | 45/5314 [02:11<5:55:55,  4.05s/it]
  1%|          | 46/5314 [02:15<5:44:15,  3.92s/it]
  1%|          | 47/5314 [02:19<6:04:37,  4.15s/it]
  1%|          | 48/5314 [02:22<5:18:31,  3.63s/it]
  1%|          | 49/5314 [02:26<5:29:49,  3.76s/it]
  1%|          | 50/5314 [02:28<4:56:50,  3.38s/it]
  1%|          | 51/5314 [02:31<4:26:16,  3.04s/it]
  1%|          | 52/5314 [02:34<4:47:33,  3.28s/it]
  1%|          | 53/5314 [02:37<4:27:30,  3.05s/it]
  1%|          | 54/5314 [02:39<4:09:12,  2.84s/it]
  1%|          | 55/5314 [02:42<4:18:27,  2.95s/it]
  1%|          | 56/5314 [02:45<4:01:17,  2.75s/it]
  1%|          | 57/5314 [02:47<3:59:28,  2.73s/it]
  1%|          | 58/5314 [02:50<3:46:53,  2.59s/it]
  1%|          | 59/5314 [02:53<4:06:06,  2.81s/it]
  1%|          | 60/5314 [02:56<4:01:25,  2.76s/it]

Error 9

  1%|          | 61/5314 [02:56<3:04:44,  2.11s/it]
  1%|          | 62/5314 [03:00<3:43:00,  2.55s/it]
  1%|          | 63/5314 [03:05<4:57:36,  3.40s/it]
  1%|          | 64/5314 [03:10<5:24:58,  3.71s/it]
  1%|          | 65/5314 [03:12<4:59:52,  3.43s/it]
  1%|          | 66/5314 [03:15<4:40:30,  3.21s/it]
  1%|▏         | 67/5314 [03:18<4:21:29,  2.99s/it]
  1%|▏         | 68/5314 [03:20<4:06:50,  2.82s/it]
  1%|▏         | 69/5314 [03:23<4:01:37,  2.76s/it]

Error 10

  1%|▏         | 70/5314 [03:23<2:59:58,  2.06s/it]
  1%|▏         | 71/5314 [03:29<4:37:45,  3.18s/it]
  1%|▏         | 72/5314 [03:32<4:24:31,  3.03s/it]
  1%|▏         | 73/5314 [03:34<4:12:58,  2.90s/it]
  1%|▏         | 74/5314 [03:38<4:47:18,  3.29s/it]
  1%|▏         | 75/5314 [03:44<5:55:20,  4.07s/it]
  1%|▏         | 76/5314 [03:47<5:30:44,  3.79s/it]
  1%|▏         | 77/5314 [03:50<4:51:38,  3.34s/it]
  1%|▏         | 78/5314 [03:52<4:24:10,  3.03s/it]
  1%|▏         | 79/5314 [03:54<4:00:41,  2.76s/it]
  2%|▏         | 80/5314 [03:58<4:20:19,  2.98s/it]
  2%|▏         | 81/5314 [04:00<4:16:40,  2.94s/it]
  2%|▏         | 82/5314 [04:06<5:16:32,  3.63s/it]
  2%|▏         | 83/5314 [04:08<4:44:07,  3.26s/it]
  2%|▏         | 84/5314 [04:12<4:55:31,  3.39s/it]
  2%|▏         | 85/5314 [04:14<4:30:39,  3.11s/it]
  2%|▏         | 86/5314 [04:17<4:15:58,  2.94s/it]
  2%|▏         | 87/5314 [04:20<4:21:46,  3.00s/it]

Error 11

  2%|▏         | 88/5314 [04:20<3:14:43,  2.24s/it]
  2%|▏         | 89/5314 [04:28<5:44:53,  3.96s/it]
  2%|▏         | 90/5314 [04:31<5:16:16,  3.63s/it]
  2%|▏         | 91/5314 [04:34<4:49:27,  3.33s/it]
  2%|▏         | 92/5314 [04:37<4:32:07,  3.13s/it]
  2%|▏         | 93/5314 [04:39<4:26:23,  3.06s/it]
  2%|▏         | 94/5314 [04:47<6:13:24,  4.29s/it]
  2%|▏         | 95/5314 [04:50<5:48:13,  4.00s/it]
  2%|▏         | 96/5314 [04:58<7:26:53,  5.14s/it]
  2%|▏         | 97/5314 [05:01<6:28:01,  4.46s/it]
  2%|▏         | 98/5314 [05:03<5:38:10,  3.89s/it]
  2%|▏         | 99/5314 [05:09<6:26:21,  4.45s/it]
  2%|▏         | 100/5314 [05:18<8:25:09,  5.81s/it]
  2%|▏         | 101/5314 [05:21<7:05:02,  4.89s/it]
  2%|▏         | 102/5314 [05:23<6:03:38,  4.19s/it]
  2%|▏         | 103/5314 [05:28<6:23:28,  4.42s/it]
  2%|▏         | 104/5314 [05:32<6:05:40,  4.21s/it]
  2%|▏         | 105/5314 [05:35<5:47:56,  4.01s/it]
  2%|▏         | 106/5314 [05:39<5:31:43,  3.82s/it]
  2%|▏         | 107/5314 [05:41<4:56:26,  3.42s/it]
  2%|▏         | 108/5314 [05:44<4:37:19,  3.20s/it]

Error 12

  2%|▏         | 109/5314 [05:44<3:25:57,  2.37s/it]
  2%|▏         | 110/5314 [05:47<3:40:29,  2.54s/it]
  2%|▏         | 111/5314 [05:51<4:03:37,  2.81s/it]
  2%|▏         | 112/5314 [05:54<4:03:23,  2.81s/it]
  2%|▏         | 113/5314 [05:56<3:49:02,  2.64s/it]
  2%|▏         | 114/5314 [05:59<3:54:28,  2.71s/it]
  2%|▏         | 115/5314 [06:02<4:05:16,  2.83s/it]
  2%|▏         | 116/5314 [06:05<4:08:35,  2.87s/it]
  2%|▏         | 117/5314 [06:08<4:08:40,  2.87s/it]
  2%|▏         | 118/5314 [06:11<4:28:04,  3.10s/it]
  2%|▏         | 119/5314 [06:14<4:27:58,  3.09s/it]
  2%|▏         | 120/5314 [06:18<4:51:59,  3.37s/it]
  2%|▏         | 121/5314 [06:21<4:26:33,  3.08s/it]

Error 13

  2%|▏         | 122/5314 [06:22<3:28:15,  2.41s/it]
  2%|▏         | 123/5314 [06:24<3:39:59,  2.54s/it]
  2%|▏         | 124/5314 [06:28<3:54:22,  2.71s/it]
  2%|▏         | 125/5314 [06:35<5:49:38,  4.04s/it]
  2%|▏         | 126/5314 [06:38<5:24:24,  3.75s/it]

Error 14

  2%|▏         | 127/5314 [06:38<3:57:33,  2.75s/it]
  2%|▏         | 128/5314 [06:42<4:29:57,  3.12s/it]
  2%|▏         | 129/5314 [06:45<4:33:12,  3.16s/it]
  2%|▏         | 130/5314 [06:48<4:24:55,  3.07s/it]

Error 15

  2%|▏         | 131/5314 [06:49<3:15:45,  2.27s/it]
  2%|▏         | 132/5314 [06:51<3:28:34,  2.42s/it]

Error 16

  3%|▎         | 133/5314 [06:52<2:40:26,  1.86s/it]

Error 17

  3%|▎         | 134/5314 [06:53<2:11:55,  1.53s/it]
  3%|▎         | 135/5314 [06:56<2:43:46,  1.90s/it]
  3%|▎         | 136/5314 [06:59<3:16:10,  2.27s/it]
  3%|▎         | 137/5314 [07:02<3:47:50,  2.64s/it]
  3%|▎         | 138/5314 [07:06<4:25:38,  3.08s/it]
  3%|▎         | 139/5314 [07:09<4:14:29,  2.95s/it]
  3%|▎         | 140/5314 [07:12<4:11:50,  2.92s/it]
  3%|▎         | 141/5314 [07:18<5:26:06,  3.78s/it]
  3%|▎         | 142/5314 [07:20<5:01:50,  3.50s/it]
  3%|▎         | 143/5314 [07:23<4:44:53,  3.31s/it]
  3%|▎         | 144/5314 [07:26<4:37:37,  3.22s/it]
  3%|▎         | 145/5314 [07:30<4:45:12,  3.31s/it]
  3%|▎         | 146/5314 [07:33<4:43:14,  3.29s/it]
  3%|▎         | 147/5314 [07:37<4:56:06,  3.44s/it]
  3%|▎         | 148/5314 [07:39<4:35:50,  3.20s/it]

Error 18

  3%|▎         | 149/5314 [07:40<3:26:40,  2.40s/it]
  3%|▎         | 150/5314 [07:44<4:04:54,  2.85s/it]
  3%|▎         | 151/5314 [07:51<5:50:15,  4.07s/it]
  3%|▎         | 152/5314 [07:56<6:15:17,  4.36s/it]
  3%|▎         | 153/5314 [07:59<5:49:46,  4.07s/it]
  3%|▎         | 154/5314 [08:02<5:13:52,  3.65s/it]
  3%|▎         | 155/5314 [08:05<4:51:13,  3.39s/it]
  3%|▎         | 156/5314 [08:08<4:43:35,  3.30s/it]
  3%|▎         | 157/5314 [08:15<6:22:09,  4.45s/it]
  3%|▎         | 158/5314 [08:18<5:50:51,  4.08s/it]
  3%|▎         | 159/5314 [08:21<5:22:13,  3.75s/it]
  3%|▎         | 160/5314 [08:24<5:12:56,  3.64s/it]
  3%|▎         | 161/5314 [08:28<4:56:44,  3.46s/it]
  3%|▎         | 162/5314 [08:31<4:57:10,  3.46s/it]
  3%|▎         | 163/5314 [08:38<6:26:27,  4.50s/it]

Error 19

  3%|▎         | 164/5314 [08:39<4:51:57,  3.40s/it]
  3%|▎         | 165/5314 [08:44<5:43:04,  4.00s/it]
  3%|▎         | 166/5314 [08:47<5:03:54,  3.54s/it]
  3%|▎         | 167/5314 [08:49<4:41:30,  3.28s/it]
  3%|▎         | 168/5314 [08:52<4:21:49,  3.05s/it]
  3%|▎         | 169/5314 [08:58<5:42:38,  4.00s/it]
  3%|▎         | 170/5314 [09:01<5:15:03,  3.67s/it]
  3%|▎         | 171/5314 [09:07<6:06:55,  4.28s/it]
  3%|▎         | 172/5314 [09:11<6:03:58,  4.25s/it]
  3%|▎         | 173/5314 [09:13<5:23:47,  3.78s/it]
  3%|▎         | 174/5314 [09:18<5:37:38,  3.94s/it]
  3%|▎         | 175/5314 [09:21<5:14:52,  3.68s/it]
  3%|▎         | 176/5314 [09:24<5:00:15,  3.51s/it]
  3%|▎         | 177/5314 [09:31<6:42:25,  4.70s/it]
  3%|▎         | 178/5314 [09:36<6:48:51,  4.78s/it]
  3%|▎         | 179/5314 [09:48<9:55:06,  6.95s/it]
  3%|▎         | 180/5314 [09:52<8:35:46,  6.03s/it]
  3%|▎         | 181/5314 [09:55<7:07:23,  5.00s/it]
  3%|▎         | 182/5314 [09:59<6:49:22,  4.79s/it]
  3%|▎         | 183/5314 [10:02<6:03:45,  4.25s/it]
  3%|▎         | 184/5314 [10:05<5:19:34,  3.74s/it]
  3%|▎         | 185/5314 [10:07<4:47:15,  3.36s/it]
  4%|▎         | 186/5314 [10:10<4:34:11,  3.21s/it]
  4%|▎         | 187/5314 [10:15<5:15:13,  3.69s/it]
  4%|▎         | 188/5314 [10:22<6:37:51,  4.66s/it]
  4%|▎         | 189/5314 [10:25<6:04:37,  4.27s/it]
  4%|▎         | 190/5314 [10:32<7:02:39,  4.95s/it]
  4%|▎         | 191/5314 [10:35<6:17:16,  4.42s/it]
  4%|▎         | 192/5314 [10:38<5:37:08,  3.95s/it]
  4%|▎         | 193/5314 [10:41<5:13:53,  3.68s/it]
  4%|▎         | 194/5314 [10:44<5:09:01,  3.62s/it]
  4%|▎         | 195/5314 [10:47<4:45:27,  3.35s/it]
  4%|▎         | 196/5314 [10:51<4:59:00,  3.51s/it]
  4%|▎         | 197/5314 [10:54<4:52:20,  3.43s/it]
  4%|▎         | 198/5314 [10:58<4:51:40,  3.42s/it]
  4%|▎         | 199/5314 [11:04<6:21:20,  4.47s/it]
  4%|▍         | 200/5314 [11:09<6:28:10,  4.55s/it]
  4%|▍         | 201/5314 [11:12<5:50:57,  4.12s/it]
  4%|▍         | 202/5314 [11:15<5:23:12,  3.79s/it]
  4%|▍         | 203/5314 [11:18<5:04:07,  3.57s/it]
  4%|▍         | 204/5314 [11:23<5:21:34,  3.78s/it]
  4%|▍         | 205/5314 [11:27<5:28:23,  3.86s/it]
  4%|▍         | 206/5314 [11:29<5:02:00,  3.55s/it]
  4%|▍         | 207/5314 [11:32<4:46:21,  3.36s/it]
  4%|▍         | 208/5314 [11:36<4:41:27,  3.31s/it]
  4%|▍         | 209/5314 [11:39<4:43:41,  3.33s/it]
  4%|▍         | 210/5314 [11:42<4:27:10,  3.14s/it]

Error 20

  4%|▍         | 211/5314 [11:42<3:20:02,  2.35s/it]
  4%|▍         | 212/5314 [11:45<3:41:45,  2.61s/it]
  4%|▍         | 213/5314 [11:55<6:27:42,  4.56s/it]

Error 21

  4%|▍         | 214/5314 [11:55<4:44:06,  3.34s/it]
  4%|▍         | 215/5314 [11:58<4:37:06,  3.26s/it]
  4%|▍         | 216/5314 [12:01<4:37:22,  3.26s/it]
  4%|▍         | 217/5314 [12:04<4:30:18,  3.18s/it]
  4%|▍         | 218/5314 [12:12<6:12:45,  4.39s/it]
  4%|▍         | 219/5314 [12:21<8:15:15,  5.83s/it]

Error 22

  4%|▍         | 220/5314 [12:21<5:58:23,  4.22s/it]
  4%|▍         | 221/5314 [12:24<5:32:49,  3.92s/it]
  4%|▍         | 222/5314 [12:33<7:40:13,  5.42s/it]
  4%|▍         | 223/5314 [12:37<6:42:20,  4.74s/it]
  4%|▍         | 224/5314 [12:43<7:21:36,  5.21s/it]
  4%|▍         | 225/5314 [12:49<7:50:34,  5.55s/it]
  4%|▍         | 226/5314 [12:52<6:43:21,  4.76s/it]
  4%|▍         | 227/5314 [12:55<5:53:12,  4.17s/it]
  4%|▍         | 228/5314 [12:59<5:59:46,  4.24s/it]
  4%|▍         | 229/5314 [13:02<5:24:27,  3.83s/it]
  4%|▍         | 230/5314 [13:05<5:00:28,  3.55s/it]

Error 23

  4%|▍         | 231/5314 [13:06<3:45:05,  2.66s/it]
  4%|▍         | 232/5314 [13:13<5:51:59,  4.16s/it]
  4%|▍         | 233/5314 [13:16<5:21:40,  3.80s/it]
  4%|▍         | 234/5314 [13:19<5:03:01,  3.58s/it]
  4%|▍         | 235/5314 [13:25<6:06:11,  4.33s/it]
  4%|▍         | 236/5314 [13:28<5:31:33,  3.92s/it]
  4%|▍         | 237/5314 [13:34<6:20:22,  4.50s/it]
  4%|▍         | 238/5314 [13:37<5:50:35,  4.14s/it]
  4%|▍         | 239/5314 [13:40<5:21:26,  3.80s/it]
  5%|▍         | 240/5314 [13:46<6:07:52,  4.35s/it]
  5%|▍         | 241/5314 [13:50<5:51:40,  4.16s/it]
  5%|▍         | 242/5314 [13:58<7:37:14,  5.41s/it]
  5%|▍         | 243/5314 [14:02<7:01:54,  4.99s/it]
  5%|▍         | 244/5314 [14:07<6:58:03,  4.95s/it]
  5%|▍         | 245/5314 [14:11<6:29:11,  4.61s/it]
  5%|▍         | 246/5314 [14:14<5:47:07,  4.11s/it]
  5%|▍         | 247/5314 [14:17<5:35:35,  3.97s/it]
  5%|▍         | 248/5314 [14:21<5:21:24,  3.81s/it]
  5%|▍         | 249/5314 [14:24<5:01:23,  3.57s/it]
  5%|▍         | 250/5314 [14:27<4:55:31,  3.50s/it]
  5%|▍         | 251/5314 [14:31<4:51:27,  3.45s/it]
  5%|▍         | 252/5314 [14:37<5:59:35,  4.26s/it]
  5%|▍         | 253/5314 [14:40<5:38:14,  4.01s/it]
  5%|▍         | 254/5314 [14:46<6:13:43,  4.43s/it]
  5%|▍         | 255/5314 [14:49<5:45:41,  4.10s/it]
  5%|▍         | 256/5314 [14:52<5:26:15,  3.87s/it]
  5%|▍         | 257/5314 [14:58<6:23:24,  4.55s/it]
  5%|▍         | 258/5314 [15:02<5:50:56,  4.16s/it]
  5%|▍         | 259/5314 [15:08<6:52:23,  4.89s/it]
  5%|▍         | 260/5314 [15:11<6:09:41,  4.39s/it]
  5%|▍         | 261/5314 [15:14<5:34:57,  3.98s/it]
  5%|▍         | 262/5314 [15:18<5:14:27,  3.73s/it]
  5%|▍         | 263/5314 [15:22<5:28:21,  3.90s/it]
  5%|▍         | 264/5314 [15:25<5:00:51,  3.57s/it]
  5%|▍         | 265/5314 [15:28<5:01:10,  3.58s/it]
  5%|▌         | 266/5314 [15:32<5:03:08,  3.60s/it]

Error 24

  5%|▌         | 267/5314 [15:32<3:45:08,  2.68s/it]
  5%|▌         | 268/5314 [15:38<4:51:26,  3.47s/it]
  5%|▌         | 269/5314 [15:41<4:40:26,  3.34s/it]

Error 25

  5%|▌         | 270/5314 [15:41<3:26:09,  2.45s/it]
  5%|▌         | 271/5314 [15:44<3:47:18,  2.70s/it]
  5%|▌         | 272/5314 [15:49<4:21:18,  3.11s/it]
  5%|▌         | 273/5314 [15:53<4:42:44,  3.37s/it]
  5%|▌         | 274/5314 [15:56<4:38:25,  3.31s/it]
  5%|▌         | 275/5314 [16:01<5:19:37,  3.81s/it]
  5%|▌         | 276/5314 [16:04<5:03:48,  3.62s/it]
  5%|▌         | 277/5314 [16:07<4:51:58,  3.48s/it]
  5%|▌         | 278/5314 [16:11<4:55:14,  3.52s/it]
  5%|▌         | 279/5314 [16:13<4:36:58,  3.30s/it]
  5%|▌         | 280/5314 [16:17<4:33:09,  3.26s/it]
  5%|▌         | 281/5314 [16:25<6:35:37,  4.72s/it]
  5%|▌         | 282/5314 [16:29<6:23:18,  4.57s/it]
  5%|▌         | 283/5314 [16:32<5:50:42,  4.18s/it]
  5%|▌         | 284/5314 [16:36<5:32:15,  3.96s/it]
  5%|▌         | 285/5314 [16:39<5:21:54,  3.84s/it]
  5%|▌         | 286/5314 [16:43<5:29:19,  3.93s/it]
  5%|▌         | 287/5314 [16:48<5:43:23,  4.10s/it]

Error 26

  5%|▌         | 288/5314 [16:48<4:11:48,  3.01s/it]

Error 27

  5%|▌         | 289/5314 [16:49<3:04:43,  2.21s/it]
  5%|▌         | 290/5314 [16:58<6:03:27,  4.34s/it]
  5%|▌         | 291/5314 [17:03<6:29:42,  4.66s/it]
  5%|▌         | 292/5314 [17:11<7:42:34,  5.53s/it]
  6%|▌         | 293/5314 [17:14<6:44:21,  4.83s/it]
  6%|▌         | 294/5314 [17:18<6:21:39,  4.56s/it]
  6%|▌         | 295/5314 [17:22<6:05:30,  4.37s/it]
  6%|▌         | 296/5314 [17:27<6:13:33,  4.47s/it]
  6%|▌         | 297/5314 [17:30<5:46:41,  4.15s/it]

Error 28

  6%|▌         | 298/5314 [17:31<4:17:05,  3.08s/it]

Error 29

  6%|▌         | 299/5314 [17:31<3:11:30,  2.29s/it]
  6%|▌         | 300/5314 [17:35<3:57:18,  2.84s/it]
  6%|▌         | 301/5314 [17:38<4:07:17,  2.96s/it]

Error 30

  6%|▌         | 302/5314 [17:39<3:04:28,  2.21s/it]
  6%|▌         | 303/5314 [17:43<3:53:27,  2.80s/it]
  6%|▌         | 304/5314 [17:51<6:04:18,  4.36s/it]
  6%|▌         | 305/5314 [17:57<6:31:18,  4.69s/it]

Error 31

  6%|▌         | 306/5314 [17:57<4:46:48,  3.44s/it]
  6%|▌         | 307/5314 [18:01<4:53:07,  3.51s/it]
  6%|▌         | 308/5314 [18:05<5:12:07,  3.74s/it]
  6%|▌         | 309/5314 [18:09<5:23:57,  3.88s/it]
  6%|▌         | 310/5314 [18:15<6:18:18,  4.54s/it]
  6%|▌         | 311/5314 [18:21<6:43:51,  4.84s/it]
  6%|▌         | 312/5314 [18:24<6:09:17,  4.43s/it]
  6%|▌         | 313/5314 [18:28<5:45:00,  4.14s/it]
  6%|▌         | 314/5314 [18:32<5:58:24,  4.30s/it]
  6%|▌         | 315/5314 [18:39<6:56:21,  5.00s/it]
  6%|▌         | 316/5314 [18:43<6:20:47,  4.57s/it]
  6%|▌         | 317/5314 [18:46<6:02:17,  4.35s/it]
  6%|▌         | 318/5314 [18:50<5:48:35,  4.19s/it]
  6%|▌         | 319/5314 [18:54<5:35:37,  4.03s/it]

Error 32

  6%|▌         | 320/5314 [18:54<4:06:22,  2.96s/it]
  6%|▌         | 321/5314 [18:58<4:21:19,  3.14s/it]
  6%|▌         | 322/5314 [19:02<4:45:56,  3.44s/it]
  6%|▌         | 323/5314 [19:06<4:59:27,  3.60s/it]
  6%|▌         | 324/5314 [19:13<6:19:43,  4.57s/it]
  6%|▌         | 325/5314 [19:16<5:54:55,  4.27s/it]
  6%|▌         | 326/5314 [19:20<5:41:47,  4.11s/it]
  6%|▌         | 327/5314 [19:24<5:37:29,  4.06s/it]
  6%|▌         | 328/5314 [19:28<5:21:07,  3.86s/it]
  6%|▌         | 329/5314 [19:32<5:41:51,  4.11s/it]
  6%|▌         | 330/5314 [19:44<8:52:48,  6.41s/it]
  6%|▌         | 331/5314 [19:49<8:27:29,  6.11s/it]
  6%|▌         | 332/5314 [19:54<7:50:48,  5.67s/it]
  6%|▋         | 333/5314 [19:57<6:53:56,  4.99s/it]
  6%|▋         | 334/5314 [20:04<7:31:02,  5.43s/it]
  6%|▋         | 335/5314 [20:11<8:13:41,  5.95s/it]
  6%|▋         | 336/5314 [20:15<7:14:26,  5.24s/it]
  6%|▋         | 337/5314 [20:21<7:41:48,  5.57s/it]
  6%|▋         | 338/5314 [20:24<6:38:29,  4.80s/it]
  6%|▋         | 339/5314 [20:27<5:59:31,  4.34s/it]
  6%|▋         | 340/5314 [20:31<5:39:29,  4.10s/it]
  6%|▋         | 341/5314 [20:34<5:19:34,  3.86s/it]
  6%|▋         | 342/5314 [20:38<5:25:09,  3.92s/it]
  6%|▋         | 343/5314 [20:42<5:10:28,  3.75s/it]
  6%|▋         | 344/5314 [20:46<5:29:00,  3.97s/it]
  6%|▋         | 345/5314 [20:50<5:38:13,  4.08s/it]
  7%|▋         | 346/5314 [20:55<5:45:12,  4.17s/it]
  7%|▋         | 347/5314 [20:58<5:32:08,  4.01s/it]
  7%|▋         | 348/5314 [21:02<5:24:40,  3.92s/it]
  7%|▋         | 349/5314 [21:06<5:21:20,  3.88s/it]
  7%|▋         | 350/5314 [21:10<5:21:56,  3.89s/it]

Error 33

  7%|▋         | 351/5314 [21:11<4:23:56,  3.19s/it]
  7%|▋         | 352/5314 [21:17<5:30:28,  4.00s/it]
  7%|▋         | 353/5314 [21:21<5:28:06,  3.97s/it]

Error 34

  7%|▋         | 354/5314 [21:22<4:04:49,  2.96s/it]
  7%|▋         | 355/5314 [21:27<4:57:22,  3.60s/it]
  7%|▋         | 356/5314 [21:30<4:44:30,  3.44s/it]
  7%|▋         | 357/5314 [21:36<5:41:01,  4.13s/it]
  7%|▋         | 358/5314 [21:40<5:46:47,  4.20s/it]
  7%|▋         | 359/5314 [21:46<6:42:44,  4.88s/it]
  7%|▋         | 360/5314 [21:50<6:20:10,  4.60s/it]
  7%|▋         | 361/5314 [21:57<7:07:39,  5.18s/it]
  7%|▋         | 362/5314 [22:00<6:24:47,  4.66s/it]
  7%|▋         | 363/5314 [22:05<6:16:47,  4.57s/it]
  7%|▋         | 364/5314 [22:09<5:59:16,  4.35s/it]
  7%|▋         | 365/5314 [22:13<6:07:17,  4.45s/it]
  7%|▋         | 366/5314 [22:17<5:50:33,  4.25s/it]
  7%|▋         | 367/5314 [22:24<7:00:25,  5.10s/it]
  7%|▋         | 368/5314 [22:28<6:23:39,  4.65s/it]
  7%|▋         | 369/5314 [22:32<6:01:39,  4.39s/it]
  7%|▋         | 370/5314 [22:36<6:08:52,  4.48s/it]
  7%|▋         | 371/5314 [22:41<6:15:12,  4.55s/it]
  7%|▋         | 372/5314 [22:48<7:17:18,  5.31s/it]
  7%|▋         | 373/5314 [22:52<6:32:50,  4.77s/it]
  7%|▋         | 374/5314 [22:55<6:03:52,  4.42s/it]
  7%|▋         | 375/5314 [22:59<5:42:32,  4.16s/it]
  7%|▋         | 376/5314 [23:02<5:32:19,  4.04s/it]

Error 35

  7%|▋         | 377/5314 [23:03<4:04:23,  2.97s/it]
  7%|▋         | 378/5314 [23:06<4:16:57,  3.12s/it]
  7%|▋         | 379/5314 [23:15<6:20:02,  4.62s/it]
  7%|▋         | 380/5314 [23:18<6:01:13,  4.39s/it]
  7%|▋         | 381/5314 [23:22<5:45:23,  4.20s/it]

Error 36

  7%|▋         | 382/5314 [23:23<4:13:03,  3.08s/it]
  7%|▋         | 383/5314 [23:26<4:17:29,  3.13s/it]
  7%|▋         | 384/5314 [23:29<4:27:14,  3.25s/it]
  7%|▋         | 385/5314 [23:38<6:42:08,  4.90s/it]

Error 37

  7%|▋         | 386/5314 [23:39<4:54:10,  3.58s/it]
  7%|▋         | 387/5314 [23:42<4:51:40,  3.55s/it]
  7%|▋         | 388/5314 [23:46<4:58:55,  3.64s/it]
  7%|▋         | 389/5314 [23:49<4:52:47,  3.57s/it]

Error 38

  7%|▋         | 390/5314 [23:50<3:36:12,  2.63s/it]
  7%|▋         | 391/5314 [23:53<3:58:23,  2.91s/it]
  7%|▋         | 392/5314 [23:57<4:26:23,  3.25s/it]
  7%|▋         | 393/5314 [24:01<4:39:39,  3.41s/it]

Error 39

  7%|▋         | 394/5314 [24:02<3:28:05,  2.54s/it]
  7%|▋         | 395/5314 [24:12<6:32:58,  4.79s/it]
  7%|▋         | 396/5314 [24:15<6:02:11,  4.42s/it]
  7%|▋         | 397/5314 [24:19<5:52:39,  4.30s/it]
  7%|▋         | 398/5314 [24:23<5:45:44,  4.22s/it]
  8%|▊         | 399/5314 [24:28<5:44:38,  4.21s/it]
  8%|▊         | 400/5314 [24:31<5:33:28,  4.07s/it]
  8%|▊         | 401/5314 [24:34<5:12:04,  3.81s/it]
  8%|▊         | 402/5314 [25:06<16:23:13, 12.01s/it]
  8%|▊         | 403/5314 [25:11<13:32:52,  9.93s/it]
  8%|▊         | 404/5314 [25:15<11:12:17,  8.22s/it]
  8%|▊         | 405/5314 [25:23<11:17:23,  8.28s/it]
  8%|▊         | 406/5314 [25:27<9:24:03,  6.90s/it]
  8%|▊         | 407/5314 [25:32<8:27:40,  6.21s/it]
  8%|▊         | 408/5314 [25:38<8:40:40,  6.37s/it]
  8%|▊         | 409/5314 [25:42<7:32:19,  5.53s/it]
  8%|▊         | 410/5314 [25:46<6:49:51,  5.01s/it]
  8%|▊         | 411/5314 [25:49<6:07:21,  4.50s/it]
  8%|▊         | 412/5314 [25:53<5:49:07,  4.27s/it]
  8%|▊         | 413/5314 [25:56<5:23:51,  3.96s/it]
  8%|▊         | 414/5314 [26:00<5:28:54,  4.03s/it]
  8%|▊         | 415/5314 [26:05<5:35:45,  4.11s/it]
  8%|▊         | 416/5314 [26:08<5:21:30,  3.94s/it]
  8%|▊         | 417/5314 [26:14<6:18:45,  4.64s/it]
  8%|▊         | 418/5314 [26:19<6:15:56,  4.61s/it]
  8%|▊         | 419/5314 [26:23<5:58:25,  4.39s/it]
  8%|▊         | 420/5314 [26:27<5:52:49,  4.33s/it]
  8%|▊         | 421/5314 [26:31<5:40:58,  4.18s/it]
  8%|▊         | 422/5314 [26:34<5:27:12,  4.01s/it]
  8%|▊         | 423/5314 [26:39<5:41:49,  4.19s/it]
  8%|▊         | 424/5314 [26:47<7:11:01,  5.29s/it]
  8%|▊         | 425/5314 [26:51<6:31:43,  4.81s/it]
  8%|▊         | 426/5314 [26:56<6:52:55,  5.07s/it]
  8%|▊         | 427/5314 [27:00<6:14:01,  4.59s/it]
  8%|▊         | 428/5314 [27:03<5:47:17,  4.26s/it]
  8%|▊         | 429/5314 [27:07<5:41:29,  4.19s/it]
  8%|▊         | 430/5314 [27:11<5:35:02,  4.12s/it]
  8%|▊         | 431/5314 [27:18<6:49:12,  5.03s/it]
  8%|▊         | 432/5314 [27:22<6:24:57,  4.73s/it]
  8%|▊         | 433/5314 [27:27<6:20:25,  4.68s/it]
  8%|▊         | 434/5314 [27:35<7:53:16,  5.82s/it]
  8%|▊         | 435/5314 [27:39<7:05:14,  5.23s/it]
  8%|▊         | 436/5314 [27:44<6:52:44,  5.08s/it]
  8%|▊         | 437/5314 [27:50<7:27:21,  5.50s/it]
  8%|▊         | 438/5314 [27:58<8:13:55,  6.08s/it]
  8%|▊         | 439/5314 [28:03<7:51:33,  5.80s/it]
  8%|▊         | 440/5314 [28:07<7:06:26,  5.25s/it]
  8%|▊         | 441/5314 [28:12<6:55:33,  5.12s/it]

Error 40

  8%|▊         | 442/5314 [28:12<5:02:00,  3.72s/it]
  8%|▊         | 443/5314 [28:21<6:57:33,  5.14s/it]
  8%|▊         | 444/5314 [28:25<6:24:15,  4.73s/it]
  8%|▊         | 445/5314 [28:32<7:33:44,  5.59s/it]
  8%|▊         | 446/5314 [28:36<6:48:11,  5.03s/it]
  8%|▊         | 447/5314 [28:40<6:19:35,  4.68s/it]

Error 41

  8%|▊         | 448/5314 [28:41<5:00:58,  3.71s/it]
  8%|▊         | 449/5314 [28:46<5:25:36,  4.02s/it]
  8%|▊         | 450/5314 [28:50<5:17:13,  3.91s/it]
  8%|▊         | 451/5314 [28:54<5:22:33,  3.98s/it]
  9%|▊         | 452/5314 [28:58<5:27:46,  4.04s/it]
  9%|▊         | 453/5314 [29:02<5:27:46,  4.05s/it]
  9%|▊         | 454/5314 [29:08<6:07:06,  4.53s/it]
  9%|▊         | 455/5314 [29:12<5:52:51,  4.36s/it]
  9%|▊         | 456/5314 [29:16<6:02:33,  4.48s/it]
  9%|▊         | 457/5314 [29:20<5:53:00,  4.36s/it]
  9%|▊         | 458/5314 [29:24<5:39:35,  4.20s/it]
  9%|▊         | 459/5314 [29:28<5:37:44,  4.17s/it]
  9%|▊         | 460/5314 [29:32<5:28:09,  4.06s/it]
  9%|▊         | 461/5314 [29:38<6:15:30,  4.64s/it]
  9%|▊         | 462/5314 [29:43<6:29:20,  4.81s/it]
  9%|▊         | 463/5314 [29:49<6:39:29,  4.94s/it]
  9%|▊         | 464/5314 [29:53<6:20:42,  4.71s/it]
  9%|▉         | 465/5314 [30:00<7:31:20,  5.58s/it]
  9%|▉         | 466/5314 [30:05<7:03:42,  5.24s/it]
  9%|▉         | 467/5314 [30:09<6:28:38,  4.81s/it]
  9%|▉         | 468/5314 [30:13<6:29:01,  4.82s/it]
  9%|▉         | 469/5314 [30:23<8:20:48,  6.20s/it]
  9%|▉         | 470/5314 [30:33<9:58:54,  7.42s/it]
  9%|▉         | 471/5314 [30:38<9:04:58,  6.75s/it]
  9%|▉         | 472/5314 [30:42<7:56:00,  5.90s/it]
  9%|▉         | 473/5314 [30:47<7:28:10,  5.55s/it]
  9%|▉         | 474/5314 [30:51<6:46:38,  5.04s/it]
  9%|▉         | 475/5314 [30:55<6:15:49,  4.66s/it]
  9%|▉         | 476/5314 [30:59<6:06:30,  4.55s/it]
  9%|▉         | 477/5314 [31:02<5:43:04,  4.26s/it]
  9%|▉         | 478/5314 [31:06<5:33:26,  4.14s/it]
  9%|▉         | 479/5314 [31:11<5:36:20,  4.17s/it]
  9%|▉         | 480/5314 [31:15<5:46:05,  4.30s/it]
  9%|▉         | 481/5314 [31:20<6:10:01,  4.59s/it]
  9%|▉         | 482/5314 [31:28<7:13:47,  5.39s/it]
  9%|▉         | 483/5314 [31:31<6:33:45,  4.89s/it]
  9%|▉         | 484/5314 [31:36<6:32:15,  4.87s/it]
  9%|▉         | 485/5314 [32:36<28:27:22, 21.21s/it]
  9%|▉         | 486/5314 [32:41<22:03:53, 16.45s/it]

Error 42

  9%|▉         | 487/5314 [32:42<15:45:51, 11.76s/it]
  9%|▉         | 488/5314 [32:49<13:53:19, 10.36s/it]
  9%|▉         | 489/5314 [32:53<11:18:33,  8.44s/it]
  9%|▉         | 490/5314 [32:57<9:31:57,  7.11s/it]
  9%|▉         | 491/5314 [33:01<8:23:15,  6.26s/it]
  9%|▉         | 492/5314 [33:06<7:42:22,  5.75s/it]
  9%|▉         | 493/5314 [33:11<7:32:56,  5.64s/it]
  9%|▉         | 494/5314 [33:16<7:12:06,  5.38s/it]
  9%|▉         | 495/5314 [33:21<7:02:14,  5.26s/it]
  9%|▉         | 496/5314 [33:25<6:29:26,  4.85s/it]
  9%|▉         | 497/5314 [33:30<6:30:22,  4.86s/it]
  9%|▉         | 498/5314 [33:33<6:06:12,  4.56s/it]
  9%|▉         | 499/5314 [33:41<7:07:17,  5.32s/it]
  9%|▉         | 500/5314 [33:44<6:31:50,  4.88s/it]
  9%|▉         | 501/5314 [33:49<6:30:21,  4.87s/it]
  9%|▉         | 502/5314 [33:57<7:49:24,  5.85s/it]
  9%|▉         | 503/5314 [34:01<7:04:19,  5.29s/it]
  9%|▉         | 504/5314 [34:05<6:33:23,  4.91s/it]
 10%|▉         | 505/5314 [34:10<6:18:07,  4.72s/it]
 10%|▉         | 506/5314 [34:17<7:21:15,  5.51s/it]
 10%|▉         | 507/5314 [34:22<7:05:15,  5.31s/it]
 10%|▉         | 508/5314 [34:26<6:33:29,  4.91s/it]
 10%|▉         | 509/5314 [34:36<8:40:48,  6.50s/it]
 10%|▉         | 510/5314 [34:40<7:47:34,  5.84s/it]
 10%|▉         | 511/5314 [34:49<8:44:38,  6.55s/it]
 10%|▉         | 512/5314 [34:53<7:57:15,  5.96s/it]
 10%|▉         | 513/5314 [34:57<7:10:22,  5.38s/it]
 10%|▉         | 514/5314 [35:02<7:07:26,  5.34s/it]
 10%|▉         | 515/5314 [35:06<6:37:25,  4.97s/it]
 10%|▉         | 516/5314 [35:11<6:21:53,  4.78s/it]
 10%|▉         | 517/5314 [35:16<6:22:45,  4.79s/it]
 10%|▉         | 518/5314 [35:22<6:51:47,  5.15s/it]
 10%|▉         | 519/5314 [35:26<6:28:21,  4.86s/it]
 10%|▉         | 520/5314 [35:30<6:12:13,  4.66s/it]
 10%|▉         | 521/5314 [35:37<7:09:16,  5.37s/it]

Error 43

 10%|▉         | 522/5314 [35:38<5:11:52,  3.91s/it]
 10%|▉         | 523/5314 [35:41<5:13:29,  3.93s/it]
 10%|▉         | 524/5314 [35:46<5:31:58,  4.16s/it]
 10%|▉         | 525/5314 [35:53<6:28:04,  4.86s/it]
 10%|▉         | 526/5314 [35:57<6:21:08,  4.78s/it]
 10%|▉         | 527/5314 [36:02<6:13:28,  4.68s/it]
 10%|▉         | 528/5314 [36:06<5:59:10,  4.50s/it]
 10%|▉         | 529/5314 [36:14<7:20:01,  5.52s/it]
 10%|▉         | 530/5314 [36:19<7:09:37,  5.39s/it]

Error 44

 10%|▉         | 531/5314 [36:20<5:22:18,  4.04s/it]
 10%|█         | 532/5314 [36:24<5:31:27,  4.16s/it]
 10%|█         | 533/5314 [36:29<5:40:47,  4.28s/it]
 10%|█         | 534/5314 [36:33<5:37:24,  4.24s/it]
 10%|█         | 535/5314 [36:37<5:42:49,  4.30s/it]
 10%|█         | 536/5314 [36:42<5:48:44,  4.38s/it]
 10%|█         | 537/5314 [36:46<5:48:58,  4.38s/it]
 10%|█         | 538/5314 [36:51<5:56:01,  4.47s/it]
 10%|█         | 539/5314 [36:55<5:54:04,  4.45s/it]
 10%|█         | 540/5314 [37:02<6:57:50,  5.25s/it]
 10%|█         | 541/5314 [37:07<6:43:21,  5.07s/it]
 10%|█         | 542/5314 [37:15<7:54:16,  5.96s/it]
 10%|█         | 543/5314 [37:29<11:14:17,  8.48s/it]
 10%|█         | 544/5314 [37:34<9:33:26,  7.21s/it]
 10%|█         | 545/5314 [37:38<8:35:09,  6.48s/it]
 10%|█         | 546/5314 [37:46<8:50:54,  6.68s/it]

Error 45

 10%|█         | 547/5314 [37:46<6:22:45,  4.82s/it]
 10%|█         | 548/5314 [37:51<6:34:52,  4.97s/it]
 10%|█         | 549/5314 [38:03<9:00:06,  6.80s/it]
 10%|█         | 550/5314 [38:07<7:55:08,  5.98s/it]
 10%|█         | 551/5314 [38:11<7:15:15,  5.48s/it]
 10%|█         | 552/5314 [38:16<6:55:39,  5.24s/it]
 10%|█         | 553/5314 [38:20<6:39:14,  5.03s/it]
 10%|█         | 554/5314 [38:24<6:20:43,  4.80s/it]
 10%|█         | 555/5314 [38:29<6:24:28,  4.85s/it]
 10%|█         | 556/5314 [38:36<7:11:32,  5.44s/it]
 10%|█         | 557/5314 [38:42<7:24:37,  5.61s/it]
 11%|█         | 558/5314 [38:46<6:54:13,  5.23s/it]
 11%|█         | 559/5314 [38:51<6:27:11,  4.89s/it]
 11%|█         | 560/5314 [38:59<7:49:32,  5.93s/it]
 11%|█         | 561/5314 [39:03<7:16:43,  5.51s/it]
 11%|█         | 562/5314 [39:08<7:03:20,  5.35s/it]
 11%|█         | 563/5314 [39:13<6:51:26,  5.20s/it]
 11%|█         | 564/5314 [39:17<6:21:07,  4.81s/it]
 11%|█         | 565/5314 [39:22<6:14:08,  4.73s/it]
 11%|█         | 566/5314 [39:25<5:50:35,  4.43s/it]
 11%|█         | 567/5314 [39:29<5:40:12,  4.30s/it]
 11%|█         | 568/5314 [39:34<5:35:22,  4.24s/it]
 11%|█         | 569/5314 [39:39<5:56:24,  4.51s/it]
 11%|█         | 570/5314 [39:44<6:07:42,  4.65s/it]
 11%|█         | 571/5314 [39:53<8:02:28,  6.10s/it]
 11%|█         | 572/5314 [39:57<7:09:32,  5.43s/it]
 11%|█         | 573/5314 [40:04<7:50:32,  5.96s/it]
 11%|█         | 574/5314 [40:12<8:39:04,  6.57s/it]
 11%|█         | 575/5314 [40:18<8:17:47,  6.30s/it]
 11%|█         | 576/5314 [40:26<9:10:17,  6.97s/it]
 11%|█         | 577/5314 [40:31<8:03:33,  6.12s/it]

Error 46

 11%|█         | 578/5314 [40:31<5:48:09,  4.41s/it]
 11%|█         | 579/5314 [40:35<5:49:28,  4.43s/it]
 11%|█         | 580/5314 [40:40<5:41:41,  4.33s/it]

Error 47

 11%|█         | 581/5314 [40:40<4:11:17,  3.19s/it]
 11%|█         | 582/5314 [40:45<4:43:38,  3.60s/it]
 11%|█         | 583/5314 [40:49<5:11:38,  3.95s/it]
 11%|█         | 584/5314 [40:54<5:35:54,  4.26s/it]
 11%|█         | 585/5314 [40:59<5:39:56,  4.31s/it]

Error 48

 11%|█         | 586/5314 [40:59<4:11:07,  3.19s/it]
 11%|█         | 587/5314 [41:07<5:45:05,  4.38s/it]
 11%|█         | 588/5314 [41:12<6:09:15,  4.69s/it]
 11%|█         | 589/5314 [41:16<6:04:27,  4.63s/it]
 11%|█         | 590/5314 [41:22<6:21:24,  4.84s/it]
 11%|█         | 591/5314 [41:26<6:08:40,  4.68s/it]
 11%|█         | 592/5314 [44:01<65:21:06, 49.82s/it]
 11%|█         | 593/5314 [44:07<47:57:16, 36.57s/it]
 11%|█         | 594/5314 [44:11<35:17:26, 26.92s/it]
 11%|█         | 595/5314 [44:24<29:35:51, 22.58s/it]
 11%|█         | 596/5314 [44:31<23:34:00, 17.98s/it]
 11%|█         | 597/5314 [44:38<19:13:07, 14.67s/it]
 11%|█▏        | 598/5314 [44:43<15:22:14, 11.73s/it]
 11%|█▏        | 599/5314 [44:50<13:25:54, 10.26s/it]
 11%|█▏        | 600/5314 [44:54<10:58:34,  8.38s/it]

Error 49

 11%|█▏        | 601/5314 [44:54<7:54:23,  6.04s/it]
 11%|█▏        | 602/5314 [44:59<7:16:40,  5.56s/it]
 11%|█▏        | 603/5314 [45:05<7:40:51,  5.87s/it]
 11%|█▏        | 604/5314 [45:09<6:56:49,  5.31s/it]

Error 50

 11%|█▏        | 605/5314 [45:11<5:27:53,  4.18s/it]
 11%|█▏        | 606/5314 [45:16<5:42:29,  4.36s/it]

Error 51

 11%|█▏        | 607/5314 [45:16<4:13:12,  3.23s/it]
 11%|█▏        | 608/5314 [45:21<4:43:30,  3.61s/it]
 11%|█▏        | 609/5314 [45:25<5:07:38,  3.92s/it]
 11%|█▏        | 610/5314 [45:30<5:24:42,  4.14s/it]
 11%|█▏        | 611/5314 [45:34<5:28:45,  4.19s/it]

Error 52

 12%|█▏        | 612/5314 [45:36<4:22:11,  3.35s/it]
 12%|█▏        | 613/5314 [45:40<4:49:31,  3.70s/it]
 12%|█▏        | 614/5314 [45:44<4:59:45,  3.83s/it]
 12%|█▏        | 615/5314 [45:49<5:28:43,  4.20s/it]
 12%|█▏        | 616/5314 [45:55<6:04:15,  4.65s/it]
 12%|█▏        | 617/5314 [46:02<6:47:04,  5.20s/it]
 12%|█▏        | 618/5314 [46:09<7:33:46,  5.80s/it]
 12%|█▏        | 619/5314 [46:13<6:54:17,  5.29s/it]
 12%|█▏        | 620/5314 [46:18<6:38:16,  5.09s/it]
 12%|█▏        | 621/5314 [46:22<6:28:13,  4.96s/it]
 12%|█▏        | 622/5314 [46:30<7:34:00,  5.81s/it]
 12%|█▏        | 623/5314 [46:35<7:08:48,  5.48s/it]
 12%|█▏        | 624/5314 [46:45<8:51:35,  6.80s/it]
 12%|█▏        | 625/5314 [46:49<8:07:16,  6.24s/it]

Error 53

 12%|█▏        | 626/5314 [46:51<6:15:36,  4.81s/it]
 12%|█▏        | 627/5314 [46:56<6:23:01,  4.90s/it]
 12%|█▏        | 628/5314 [47:01<6:17:13,  4.83s/it]
 12%|█▏        | 629/5314 [47:06<6:19:50,  4.86s/it]
 12%|█▏        | 630/5314 [47:12<6:57:43,  5.35s/it]
 12%|█▏        | 631/5314 [47:19<7:40:04,  5.89s/it]
 12%|█▏        | 632/5314 [47:24<7:08:23,  5.49s/it]
 12%|█▏        | 633/5314 [47:28<6:40:12,  5.13s/it]
 12%|█▏        | 634/5314 [47:32<6:20:47,  4.88s/it]
 12%|█▏        | 635/5314 [47:38<6:25:57,  4.95s/it]
 12%|█▏        | 636/5314 [47:42<6:21:39,  4.90s/it]
 12%|█▏        | 637/5314 [47:48<6:37:45,  5.10s/it]
 12%|█▏        | 638/5314 [47:53<6:30:31,  5.01s/it]

Error 54

 12%|█▏        | 639/5314 [47:54<5:09:06,  3.97s/it]
 12%|█▏        | 640/5314 [48:01<6:11:00,  4.76s/it]
 12%|█▏        | 641/5314 [48:05<6:07:34,  4.72s/it]
 12%|█▏        | 642/5314 [48:10<6:07:08,  4.72s/it]
 12%|█▏        | 643/5314 [48:15<6:15:18,  4.82s/it]
 12%|█▏        | 644/5314 [48:20<6:22:28,  4.91s/it]
 12%|█▏        | 645/5314 [48:26<6:28:01,  4.99s/it]
 12%|█▏        | 646/5314 [48:32<7:12:07,  5.55s/it]
 12%|█▏        | 647/5314 [48:37<6:56:09,  5.35s/it]
 12%|█▏        | 648/5314 [48:43<7:10:47,  5.54s/it]
 12%|█▏        | 649/5314 [48:48<6:53:00,  5.31s/it]
 12%|█▏        | 650/5314 [48:56<7:46:51,  6.01s/it]
 12%|█▏        | 651/5314 [49:03<8:18:18,  6.41s/it]
 12%|█▏        | 652/5314 [49:08<7:37:04,  5.88s/it]
 12%|█▏        | 653/5314 [49:13<7:23:37,  5.71s/it]
 12%|█▏        | 654/5314 [49:18<7:17:15,  5.63s/it]
 12%|█▏        | 655/5314 [49:23<7:00:41,  5.42s/it]
 12%|█▏        | 656/5314 [49:28<6:43:34,  5.20s/it]
 12%|█▏        | 657/5314 [49:36<7:57:22,  6.15s/it]
 12%|█▏        | 658/5314 [49:41<7:13:18,  5.58s/it]
 12%|█▏        | 659/5314 [49:45<6:40:50,  5.17s/it]
 12%|█▏        | 660/5314 [49:50<6:35:21,  5.10s/it]
 12%|█▏        | 661/5314 [49:54<6:12:10,  4.80s/it]
 12%|█▏        | 662/5314 [49:59<6:14:23,  4.83s/it]
 12%|█▏        | 663/5314 [50:03<6:00:22,  4.65s/it]
 12%|█▏        | 664/5314 [50:09<6:31:06,  5.05s/it]
 13%|█▎        | 665/5314 [50:15<6:45:07,  5.23s/it]

Error 55

 13%|█▎        | 666/5314 [50:15<4:54:12,  3.80s/it]

Error 56

 13%|█▎        | 667/5314 [50:16<3:37:43,  2.81s/it]
 13%|█▎        | 668/5314 [50:21<4:25:27,  3.43s/it]
 13%|█▎        | 669/5314 [50:25<4:46:13,  3.70s/it]

Error 57

 13%|█▎        | 670/5314 [50:25<3:32:14,  2.74s/it]
 13%|█▎        | 671/5314 [50:30<4:09:39,  3.23s/it]
 13%|█▎        | 672/5314 [50:34<4:42:11,  3.65s/it]
 13%|█▎        | 673/5314 [50:39<5:07:33,  3.98s/it]
 13%|█▎        | 674/5314 [50:44<5:31:22,  4.28s/it]
 13%|█▎        | 675/5314 [50:51<6:42:49,  5.21s/it]
 13%|█▎        | 676/5314 [51:01<8:20:53,  6.48s/it]
 13%|█▎        | 677/5314 [51:06<7:51:51,  6.11s/it]
 13%|█▎        | 678/5314 [51:11<7:22:41,  5.73s/it]
 13%|█▎        | 679/5314 [51:15<6:53:13,  5.35s/it]
 13%|█▎        | 680/5314 [51:20<6:43:28,  5.22s/it]
 13%|█▎        | 681/5314 [51:25<6:31:27,  5.07s/it]
 13%|█▎        | 682/5314 [51:31<6:53:05,  5.35s/it]
 13%|█▎        | 683/5314 [51:36<6:45:45,  5.26s/it]
 13%|█▎        | 684/5314 [51:40<6:24:48,  4.99s/it]
 13%|█▎        | 685/5314 [51:45<6:17:42,  4.90s/it]
 13%|█▎        | 686/5314 [51:50<6:07:11,  4.76s/it]
 13%|█▎        | 687/5314 [51:55<6:27:41,  5.03s/it]
 13%|█▎        | 688/5314 [52:06<8:50:18,  6.88s/it]
 13%|█▎        | 689/5314 [52:11<7:48:07,  6.07s/it]
 13%|█▎        | 690/5314 [52:16<7:21:40,  5.73s/it]
 13%|█▎        | 691/5314 [52:23<8:11:40,  6.38s/it]
 13%|█▎        | 692/5314 [52:28<7:32:56,  5.88s/it]
 13%|█▎        | 693/5314 [52:33<7:01:33,  5.47s/it]
 13%|█▎        | 694/5314 [52:39<7:12:56,  5.62s/it]
 13%|█▎        | 695/5314 [52:44<6:56:09,  5.41s/it]
 13%|█▎        | 696/5314 [52:48<6:35:15,  5.14s/it]
 13%|█▎        | 697/5314 [52:56<7:41:31,  6.00s/it]
 13%|█▎        | 698/5314 [53:01<7:13:18,  5.63s/it]
 13%|█▎        | 699/5314 [53:05<6:46:26,  5.28s/it]
 13%|█▎        | 700/5314 [53:11<6:59:26,  5.45s/it]
 13%|█▎        | 701/5314 [53:18<7:33:00,  5.89s/it]
 13%|█▎        | 702/5314 [53:23<7:14:17,  5.65s/it]

Error 58

 13%|█▎        | 703/5314 [53:24<5:15:42,  4.11s/it]
 13%|█▎        | 704/5314 [53:28<5:30:26,  4.30s/it]
 13%|█▎        | 705/5314 [53:36<6:49:20,  5.33s/it]
 13%|█▎        | 706/5314 [53:41<6:44:15,  5.26s/it]
 13%|█▎        | 707/5314 [53:46<6:34:07,  5.13s/it]
 13%|█▎        | 708/5314 [53:52<7:01:46,  5.49s/it]
 13%|█▎        | 709/5314 [54:00<7:47:54,  6.10s/it]
 13%|█▎        | 710/5314 [54:08<8:37:53,  6.75s/it]
 13%|█▎        | 711/5314 [54:17<9:23:25,  7.34s/it]

Error 59

 13%|█▎        | 712/5314 [54:18<6:47:00,  5.31s/it]
 13%|█▎        | 713/5314 [54:22<6:33:55,  5.14s/it]
 13%|█▎        | 714/5314 [54:28<6:39:01,  5.20s/it]
 13%|█▎        | 715/5314 [54:36<7:56:25,  6.22s/it]
 13%|█▎        | 716/5314 [54:41<7:23:34,  5.79s/it]
 13%|█▎        | 717/5314 [54:46<7:01:38,  5.50s/it]
 14%|█▎        | 718/5314 [54:51<6:58:43,  5.47s/it]
 14%|█▎        | 719/5314 [54:56<6:49:04,  5.34s/it]
 14%|█▎        | 720/5314 [55:01<6:41:13,  5.24s/it]
 14%|█▎        | 721/5314 [58:37<86:57:18, 68.16s/it]
 14%|█▎        | 722/5314 [58:44<63:41:20, 49.93s/it]
 14%|█▎        | 723/5314 [58:49<46:26:29, 36.42s/it]
 14%|█▎        | 724/5314 [58:53<34:23:44, 26.98s/it]
 14%|█▎        | 725/5314 [58:58<25:54:30, 20.32s/it]
 14%|█▎        | 726/5314 [59:04<20:09:39, 15.82s/it]
 14%|█▎        | 727/5314 [59:09<16:16:18, 12.77s/it]
 14%|█▎        | 728/5314 [59:14<13:10:17, 10.34s/it]
 14%|█▎        | 729/5314 [59:20<11:32:55,  9.07s/it]
 14%|█▎        | 730/5314 [59:25<9:50:14,  7.73s/it]
 14%|█▍        | 731/5314 [59:29<8:44:53,  6.87s/it]
 14%|█▍        | 732/5314 [59:38<9:18:34,  7.31s/it]
 14%|█▍        | 733/5314 [59:43<8:31:34,  6.70s/it]
 14%|█▍        | 734/5314 [59:48<7:49:33,  6.15s/it]
 14%|█▍        | 735/5314 [59:53<7:31:59,  5.92s/it]

Error 60

 14%|█▍        | 736/5314 [59:54<5:26:49,  4.28s/it]
 14%|█▍        | 737/5314 [59:59<5:49:32,  4.58s/it]
 14%|█▍        | 738/5314 [1:00:04<5:58:25,  4.70s/it]
 14%|█▍        | 739/5314 [1:00:09<6:14:43,  4.91s/it]
 14%|█▍        | 740/5314 [1:00:14<6:10:42,  4.86s/it]
 14%|█▍        | 741/5314 [1:00:19<6:17:44,  4.96s/it]
 14%|█▍        | 742/5314 [1:00:24<6:13:33,  4.90s/it]

Error 61

 14%|█▍        | 743/5314 [1:00:25<4:32:24,  3.58s/it]
 14%|█▍        | 744/5314 [1:00:30<5:15:46,  4.15s/it]
 14%|█▍        | 745/5314 [1:00:40<7:22:04,  5.81s/it]
 14%|█▍        | 746/5314 [1:00:46<7:29:28,  5.90s/it]
 14%|█▍        | 747/5314 [1:00:54<8:20:32,  6.58s/it]
 14%|█▍        | 748/5314 [1:01:00<7:59:59,  6.31s/it]
 14%|█▍        | 749/5314 [1:01:05<7:39:07,  6.03s/it]
 14%|█▍        | 750/5314 [1:01:11<7:23:35,  5.83s/it]
 14%|█▍        | 751/5314 [1:01:15<7:00:14,  5.53s/it]
 14%|█▍        | 752/5314 [1:01:20<6:44:24,  5.32s/it]
 14%|█▍        | 753/5314 [1:01:25<6:40:26,  5.27s/it]
 14%|█▍        | 754/5314 [1:01:31<6:54:59,  5.46s/it]
 14%|█▍        | 755/5314 [1:01:36<6:38:50,  5.25s/it]
 14%|█▍        | 756/5314 [1:01:41<6:39:39,  5.26s/it]
 14%|█▍        | 757/5314 [1:01:47<6:56:17,  5.48s/it]

Error 62

 14%|█▍        | 758/5314 [1:01:48<5:01:30,  3.97s/it]
 14%|█▍        | 759/5314 [1:01:53<5:22:29,  4.25s/it]
 14%|█▍        | 760/5314 [1:01:58<5:45:32,  4.55s/it]
 14%|█▍        | 761/5314 [1:02:03<6:00:47,  4.75s/it]

Error 63

 14%|█▍        | 762/5314 [1:02:04<4:25:34,  3.50s/it]
 14%|█▍        | 763/5314 [1:02:09<4:59:40,  3.95s/it]
 14%|█▍        | 764/5314 [1:02:18<7:09:38,  5.67s/it]
 14%|█▍        | 765/5314 [1:02:24<7:09:03,  5.66s/it]

Error 64

 14%|█▍        | 766/5314 [1:02:26<5:41:53,  4.51s/it]
 14%|█▍        | 767/5314 [1:02:32<6:20:53,  5.03s/it]
 14%|█▍        | 768/5314 [1:02:37<6:28:23,  5.13s/it]
 14%|█▍        | 769/5314 [1:02:43<6:28:06,  5.12s/it]
 14%|█▍        | 770/5314 [1:02:48<6:43:42,  5.33s/it]

Error 65

 15%|█▍        | 771/5314 [1:02:50<5:17:02,  4.19s/it]
 15%|█▍        | 772/5314 [1:02:55<5:47:28,  4.59s/it]
 15%|█▍        | 773/5314 [1:03:01<6:11:54,  4.91s/it]
 15%|█▍        | 774/5314 [1:03:06<6:14:25,  4.95s/it]
 15%|█▍        | 775/5314 [1:03:11<6:16:22,  4.98s/it]
 15%|█▍        | 776/5314 [1:03:16<6:09:10,  4.88s/it]
 15%|█▍        | 777/5314 [1:03:22<6:41:21,  5.31s/it]
 15%|█▍        | 778/5314 [1:03:27<6:37:46,  5.26s/it]
 15%|█▍        | 779/5314 [1:03:32<6:34:38,  5.22s/it]
 15%|█▍        | 780/5314 [1:03:40<7:32:29,  5.99s/it]
 15%|█▍        | 781/5314 [1:03:46<7:20:10,  5.83s/it]
 15%|█▍        | 782/5314 [1:03:53<7:57:48,  6.33s/it]

Error 66

 15%|█▍        | 783/5314 [1:03:54<5:46:40,  4.59s/it]
 15%|█▍        | 784/5314 [1:03:59<5:53:33,  4.68s/it]
 15%|█▍        | 785/5314 [1:04:03<5:56:46,  4.73s/it]
 15%|█▍        | 786/5314 [1:04:09<6:06:53,  4.86s/it]
 15%|█▍        | 787/5314 [1:04:14<6:11:07,  4.92s/it]
 15%|█▍        | 788/5314 [1:04:21<7:11:28,  5.72s/it]
 15%|█▍        | 789/5314 [1:04:26<6:52:34,  5.47s/it]
 15%|█▍        | 790/5314 [1:04:31<6:48:22,  5.42s/it]
 15%|█▍        | 791/5314 [1:04:37<6:58:42,  5.55s/it]
 15%|█▍        | 792/5314 [1:04:42<6:47:11,  5.40s/it]
 15%|█▍        | 793/5314 [1:04:47<6:41:09,  5.32s/it]

Error 67

 15%|█▍        | 794/5314 [1:04:49<5:15:43,  4.19s/it]
 15%|█▍        | 795/5314 [1:04:54<5:34:08,  4.44s/it]
 15%|█▍        | 796/5314 [1:05:00<6:07:06,  4.88s/it]
 15%|█▍        | 797/5314 [1:05:05<6:16:27,  5.00s/it]
 15%|█▌        | 798/5314 [1:05:11<6:38:10,  5.29s/it]
 15%|█▌        | 799/5314 [1:05:16<6:38:59,  5.30s/it]
 15%|█▌        | 800/5314 [1:05:22<6:39:01,  5.30s/it]
 15%|█▌        | 801/5314 [1:05:27<6:38:35,  5.30s/it]
 15%|█▌        | 802/5314 [1:05:32<6:39:45,  5.32s/it]
 15%|█▌        | 803/5314 [1:05:37<6:33:03,  5.23s/it]
 15%|█▌        | 804/5314 [1:05:43<6:34:04,  5.24s/it]
 15%|█▌        | 805/5314 [1:05:49<7:08:03,  5.70s/it]
 15%|█▌        | 806/5314 [1:05:55<7:12:36,  5.76s/it]
 15%|█▌        | 807/5314 [1:06:01<7:01:22,  5.61s/it]
 15%|█▌        | 808/5314 [1:06:06<6:59:18,  5.58s/it]
 15%|█▌        | 809/5314 [1:06:15<8:19:07,  6.65s/it]

Error 68

 15%|█▌        | 810/5314 [1:06:16<6:01:35,  4.82s/it]
 15%|█▌        | 811/5314 [1:06:22<6:39:04,  5.32s/it]
 15%|█▌        | 812/5314 [1:06:30<7:23:49,  5.91s/it]
 15%|█▌        | 813/5314 [1:06:35<7:20:14,  5.87s/it]
 15%|█▌        | 814/5314 [1:06:41<7:08:14,  5.71s/it]
 15%|█▌        | 815/5314 [1:06:46<7:03:34,  5.65s/it]
 15%|█▌        | 816/5314 [1:06:51<6:53:01,  5.51s/it]
 15%|█▌        | 817/5314 [1:07:00<7:55:17,  6.34s/it]
 15%|█▌        | 818/5314 [1:07:05<7:34:47,  6.07s/it]
 15%|█▌        | 819/5314 [1:07:10<7:17:08,  5.84s/it]
 15%|█▌        | 820/5314 [1:07:16<7:07:26,  5.71s/it]
 15%|█▌        | 821/5314 [1:07:24<7:59:23,  6.40s/it]
 15%|█▌        | 822/5314 [1:07:30<7:59:56,  6.41s/it]
 15%|█▌        | 823/5314 [1:07:36<7:49:01,  6.27s/it]
 16%|█▌        | 824/5314 [1:07:42<7:28:02,  5.99s/it]
 16%|█▌        | 825/5314 [1:07:48<7:47:19,  6.25s/it]
 16%|█▌        | 826/5314 [1:07:53<7:20:09,  5.88s/it]
 16%|█▌        | 827/5314 [1:08:00<7:38:45,  6.13s/it]
 16%|█▌        | 828/5314 [1:08:05<7:19:37,  5.88s/it]

Error 69

 16%|█▌        | 829/5314 [1:08:06<5:23:49,  4.33s/it]
 16%|█▌        | 830/5314 [1:08:20<8:56:05,  7.17s/it]
 16%|█▌        | 831/5314 [1:08:25<8:17:41,  6.66s/it]
 16%|█▌        | 832/5314 [1:08:31<7:57:32,  6.39s/it]
 16%|█▌        | 833/5314 [1:08:38<8:02:23,  6.46s/it]

Error 70

 16%|█▌        | 834/5314 [1:08:39<6:07:03,  4.92s/it]
 16%|█▌        | 835/5314 [1:08:45<6:21:47,  5.11s/it]
 16%|█▌        | 836/5314 [1:08:51<6:37:47,  5.33s/it]
 16%|█▌        | 837/5314 [1:08:56<6:31:10,  5.24s/it]
 16%|█▌        | 838/5314 [1:09:01<6:32:55,  5.27s/it]
 16%|█▌        | 839/5314 [1:09:07<6:48:11,  5.47s/it]
 16%|█▌        | 840/5314 [1:09:12<6:38:55,  5.35s/it]
 16%|█▌        | 841/5314 [1:09:18<6:50:32,  5.51s/it]
 16%|█▌        | 842/5314 [1:09:24<6:58:10,  5.61s/it]
 16%|█▌        | 843/5314 [1:09:29<6:51:13,  5.52s/it]
 16%|█▌        | 844/5314 [1:09:35<7:00:10,  5.64s/it]
 16%|█▌        | 845/5314 [1:09:40<6:54:14,  5.56s/it]

Error 71

 16%|█▌        | 846/5314 [1:09:42<5:24:29,  4.36s/it]
 16%|█▌        | 847/5314 [1:09:48<6:06:58,  4.93s/it]
 16%|█▌        | 848/5314 [1:09:54<6:20:25,  5.11s/it]
 16%|█▌        | 849/5314 [1:09:59<6:22:20,  5.14s/it]
 16%|█▌        | 850/5314 [1:10:08<7:48:34,  6.30s/it]
 16%|█▌        | 851/5314 [1:10:13<7:34:10,  6.11s/it]
 16%|█▌        | 852/5314 [1:10:18<7:08:59,  5.77s/it]
 16%|█▌        | 853/5314 [1:10:24<7:09:10,  5.77s/it]
 16%|█▌        | 854/5314 [1:10:32<7:59:12,  6.45s/it]
 16%|█▌        | 855/5314 [1:10:38<7:43:00,  6.23s/it]
 16%|█▌        | 856/5314 [1:10:45<7:56:21,  6.41s/it]
 16%|█▌        | 857/5314 [1:10:51<7:41:09,  6.21s/it]
 16%|█▌        | 858/5314 [1:11:00<8:47:33,  7.10s/it]
 16%|█▌        | 859/5314 [1:11:06<8:28:25,  6.85s/it]
 16%|█▌        | 860/5314 [1:11:12<8:20:37,  6.74s/it]
 16%|█▌        | 861/5314 [1:11:18<7:45:40,  6.27s/it]
 16%|█▌        | 862/5314 [1:11:23<7:25:12,  6.00s/it]

Error 72

 16%|█▌        | 863/5314 [1:11:25<5:46:39,  4.67s/it]
 16%|█▋        | 864/5314 [1:11:34<7:28:36,  6.05s/it]
 16%|█▋        | 865/5314 [1:11:40<7:29:12,  6.06s/it]
 16%|█▋        | 866/5314 [1:11:48<8:23:08,  6.79s/it]
 16%|█▋        | 867/5314 [1:11:55<8:20:31,  6.75s/it]
 16%|█▋        | 868/5314 [1:12:01<7:51:13,  6.36s/it]
 16%|█▋        | 869/5314 [1:12:08<8:09:56,  6.61s/it]
 16%|█▋        | 870/5314 [1:12:14<7:54:44,  6.41s/it]
 16%|█▋        | 871/5314 [1:12:19<7:35:43,  6.15s/it]
 16%|█▋        | 872/5314 [1:12:29<8:48:54,  7.14s/it]
 16%|█▋        | 873/5314 [1:12:37<9:18:27,  7.55s/it]
 16%|█▋        | 874/5314 [1:12:45<9:28:06,  7.68s/it]

Error 73

 16%|█▋        | 875/5314 [1:12:46<6:50:00,  5.54s/it]
 16%|█▋        | 876/5314 [1:12:51<6:48:01,  5.52s/it]
 17%|█▋        | 877/5314 [1:12:57<7:05:14,  5.75s/it]
 17%|█▋        | 878/5314 [1:17:21<102:07:57, 82.88s/it]
 17%|█▋        | 879/5314 [1:17:27<74:04:00, 60.12s/it]
 17%|█▋        | 880/5314 [1:17:33<54:05:22, 43.92s/it]
 17%|█▋        | 881/5314 [1:17:41<40:44:30, 33.09s/it]

Error 74

 17%|█▋        | 882/5314 [1:17:42<28:40:59, 23.30s/it]
 17%|█▋        | 883/5314 [1:17:48<22:23:45, 18.20s/it]
 17%|█▋        | 884/5314 [1:17:55<18:11:36, 14.78s/it]
 17%|█▋        | 885/5314 [1:18:05<16:38:01, 13.52s/it]
 17%|█▋        | 886/5314 [1:18:13<14:18:16, 11.63s/it]
 17%|█▋        | 887/5314 [1:18:19<12:15:16,  9.97s/it]
 17%|█▋        | 888/5314 [1:18:24<10:37:09,  8.64s/it]
 17%|█▋        | 889/5314 [1:18:31<9:48:32,  7.98s/it]
 17%|█▋        | 890/5314 [1:18:36<8:59:01,  7.31s/it]
 17%|█▋        | 891/5314 [1:18:42<8:26:17,  6.87s/it]
 17%|█▋        | 892/5314 [1:18:48<7:56:27,  6.46s/it]
 17%|█▋        | 893/5314 [1:18:53<7:35:33,  6.18s/it]
 17%|█▋        | 894/5314 [1:18:58<7:09:31,  5.83s/it]

Error 75

 17%|█▋        | 895/5314 [1:18:59<5:09:13,  4.20s/it]
 17%|█▋        | 896/5314 [1:19:04<5:37:12,  4.58s/it]
 17%|█▋        | 897/5314 [1:19:12<6:48:22,  5.55s/it]
 17%|█▋        | 898/5314 [1:19:17<6:43:40,  5.48s/it]
 17%|█▋        | 899/5314 [1:19:23<6:37:02,  5.40s/it]
 17%|█▋        | 900/5314 [1:19:29<6:51:39,  5.60s/it]
 17%|█▋        | 901/5314 [1:19:35<7:10:24,  5.85s/it]
 17%|█▋        | 902/5314 [1:19:41<7:17:22,  5.95s/it]
 17%|█▋        | 903/5314 [1:19:48<7:27:36,  6.09s/it]

Error 76

 17%|█▋        | 904/5314 [1:19:48<5:23:13,  4.40s/it]
 17%|█▋        | 905/5314 [1:19:54<5:57:13,  4.86s/it]
 17%|█▋        | 906/5314 [1:20:00<6:29:27,  5.30s/it]
 17%|█▋        | 907/5314 [1:20:07<6:53:44,  5.63s/it]
 17%|█▋        | 908/5314 [1:20:13<6:57:05,  5.68s/it]
 17%|█▋        | 909/5314 [1:20:22<8:13:58,  6.73s/it]

Error 77

 17%|█▋        | 910/5314 [1:20:22<6:02:19,  4.94s/it]
 17%|█▋        | 911/5314 [1:20:29<6:42:15,  5.48s/it]
 17%|█▋        | 912/5314 [1:20:35<6:55:20,  5.66s/it]
 17%|█▋        | 913/5314 [1:20:41<6:58:16,  5.70s/it]

Error 78

 17%|█▋        | 914/5314 [1:20:42<5:04:11,  4.15s/it]
 17%|█▋        | 915/5314 [1:20:51<7:04:37,  5.79s/it]
 17%|█▋        | 916/5314 [1:21:01<8:34:38,  7.02s/it]
 17%|█▋        | 917/5314 [1:21:07<8:03:43,  6.60s/it]
 17%|█▋        | 918/5314 [1:21:13<7:51:44,  6.44s/it]
 17%|█▋        | 919/5314 [1:21:21<8:27:32,  6.93s/it]
 17%|█▋        | 920/5314 [1:21:39<12:27:32, 10.21s/it]
 17%|█▋        | 921/5314 [1:21:45<10:51:31,  8.90s/it]
 17%|█▋        | 922/5314 [1:21:50<9:37:20,  7.89s/it]
 17%|█▋        | 923/5314 [1:21:56<8:48:26,  7.22s/it]
 17%|█▋        | 924/5314 [1:22:02<8:16:51,  6.79s/it]
 17%|█▋        | 925/5314 [1:22:09<8:41:19,  7.13s/it]
 17%|█▋        | 926/5314 [1:22:15<8:11:03,  6.71s/it]
 17%|█▋        | 927/5314 [1:22:22<8:17:01,  6.80s/it]
 17%|█▋        | 928/5314 [1:22:28<7:58:36,  6.55s/it]
 17%|█▋        | 929/5314 [1:22:34<7:37:08,  6.26s/it]
 18%|█▊        | 930/5314 [1:22:41<8:02:09,  6.60s/it]
 18%|█▊        | 931/5314 [1:22:47<7:41:59,  6.32s/it]
 18%|█▊        | 932/5314 [1:22:53<7:39:24,  6.29s/it]
 18%|█▊        | 933/5314 [1:23:03<9:08:34,  7.51s/it]
 18%|█▊        | 934/5314 [1:23:09<8:35:29,  7.06s/it]
 18%|█▊        | 935/5314 [1:23:16<8:25:51,  6.93s/it]
 18%|█▊        | 936/5314 [1:23:22<8:03:32,  6.63s/it]
 18%|█▊        | 937/5314 [1:23:29<8:04:21,  6.64s/it]
 18%|█▊        | 938/5314 [1:23:36<8:19:20,  6.85s/it]
 18%|█▊        | 939/5314 [1:23:42<7:56:58,  6.54s/it]
 18%|█▊        | 940/5314 [1:23:48<7:59:29,  6.58s/it]
 18%|█▊        | 941/5314 [1:23:54<7:40:36,  6.32s/it]
 18%|█▊        | 942/5314 [1:24:00<7:27:57,  6.15s/it]
 18%|█▊        | 943/5314 [1:24:07<7:40:20,  6.32s/it]
 18%|█▊        | 944/5314 [1:24:13<7:41:04,  6.33s/it]
 18%|█▊        | 945/5314 [1:24:19<7:32:46,  6.22s/it]
 18%|█▊        | 946/5314 [1:24:25<7:24:14,  6.10s/it]
 18%|█▊        | 947/5314 [1:24:31<7:21:07,  6.06s/it]
 18%|█▊        | 948/5314 [1:24:39<8:01:59,  6.62s/it]
 18%|█▊        | 949/5314 [1:24:45<7:52:13,  6.49s/it]

Error 79

 18%|█▊        | 950/5314 [1:24:45<5:43:05,  4.72s/it]
 18%|█▊        | 951/5314 [1:24:51<6:07:44,  5.06s/it]
 18%|█▊        | 952/5314 [1:25:06<9:30:37,  7.85s/it]
 18%|█▊        | 953/5314 [1:25:12<8:47:46,  7.26s/it]
 18%|█▊        | 954/5314 [1:25:18<8:35:04,  7.09s/it]
 18%|█▊        | 955/5314 [1:25:26<8:55:33,  7.37s/it]
 18%|█▊        | 956/5314 [1:25:32<8:17:57,  6.86s/it]

Error 80

 18%|█▊        | 957/5314 [1:25:32<5:59:48,  4.95s/it]
 18%|█▊        | 958/5314 [1:25:38<6:19:47,  5.23s/it]
 18%|█▊        | 959/5314 [1:25:45<7:00:44,  5.80s/it]
 18%|█▊        | 960/5314 [1:25:56<8:35:50,  7.11s/it]
 18%|█▊        | 961/5314 [1:26:05<9:16:55,  7.68s/it]
 18%|█▊        | 962/5314 [1:26:11<8:43:20,  7.22s/it]
 18%|█▊        | 963/5314 [1:26:17<8:19:08,  6.88s/it]
 18%|█▊        | 964/5314 [1:26:23<7:59:33,  6.61s/it]
 18%|█▊        | 965/5314 [1:26:33<9:05:33,  7.53s/it]
 18%|█▊        | 966/5314 [1:26:39<8:39:16,  7.17s/it]
 18%|█▊        | 967/5314 [1:26:45<8:06:59,  6.72s/it]
 18%|█▊        | 968/5314 [1:26:51<8:03:45,  6.68s/it]
 18%|█▊        | 969/5314 [1:26:58<8:16:06,  6.85s/it]
 18%|█▊        | 970/5314 [1:27:04<7:46:31,  6.44s/it]
 18%|█▊        | 971/5314 [1:27:10<7:36:21,  6.30s/it]
 18%|█▊        | 972/5314 [1:27:17<7:48:19,  6.47s/it]
 18%|█▊        | 973/5314 [1:27:22<7:31:28,  6.24s/it]
 18%|█▊        | 974/5314 [1:27:29<7:40:50,  6.37s/it]
 18%|█▊        | 975/5314 [1:27:35<7:35:11,  6.29s/it]
 18%|█▊        | 976/5314 [1:27:42<7:46:50,  6.46s/it]
 18%|█▊        | 977/5314 [1:27:48<7:41:10,  6.38s/it]
 18%|█▊        | 978/5314 [1:27:57<8:31:54,  7.08s/it]
 18%|█▊        | 979/5314 [1:28:04<8:23:10,  6.96s/it]
 18%|█▊        | 980/5314 [1:28:10<8:12:58,  6.82s/it]
 18%|█▊        | 981/5314 [1:28:19<8:50:39,  7.35s/it]
 18%|█▊        | 982/5314 [1:28:25<8:18:30,  6.90s/it]
 18%|█▊        | 983/5314 [1:28:31<8:10:46,  6.80s/it]
 19%|█▊        | 984/5314 [1:28:42<9:38:33,  8.02s/it]
 19%|█▊        | 985/5314 [1:28:51<9:54:17,  8.24s/it]
 19%|█▊        | 986/5314 [1:28:57<9:17:54,  7.73s/it]
 19%|█▊        | 987/5314 [1:29:07<9:58:23,  8.30s/it]
 19%|█▊        | 988/5314 [1:29:14<9:37:04,  8.00s/it]

Error 81

 19%|█▊        | 989/5314 [1:29:15<6:55:24,  5.76s/it]
 19%|█▊        | 990/5314 [1:29:21<6:59:27,  5.82s/it]
 19%|█▊        | 991/5314 [1:29:27<7:05:34,  5.91s/it]
 19%|█▊        | 992/5314 [1:29:38<9:08:08,  7.61s/it]
 19%|█▊        | 993/5314 [1:29:45<8:48:13,  7.33s/it]
 19%|█▊        | 994/5314 [1:29:51<8:17:38,  6.91s/it]
 19%|█▊        | 995/5314 [1:29:59<8:30:23,  7.09s/it]
 19%|█▊        | 996/5314 [1:30:05<8:20:57,  6.96s/it]
 19%|█▉        | 997/5314 [1:30:13<8:29:18,  7.08s/it]
 19%|█▉        | 998/5314 [1:30:19<8:21:20,  6.97s/it]

Error 82

 19%|█▉        | 999/5314 [1:30:20<6:03:19,  5.05s/it]

Error 83

 19%|█▉        | 1000/5314 [1:30:20<4:24:54,  3.68s/it]
 19%|█▉        | 1001/5314 [1:30:27<5:23:58,  4.51s/it]
 19%|█▉        | 1002/5314 [1:30:34<6:17:48,  5.26s/it]
 19%|█▉        | 1003/5314 [1:30:40<6:33:49,  5.48s/it]
 19%|█▉        | 1004/5314 [1:30:48<7:32:13,  6.30s/it]
 19%|█▉        | 1005/5314 [1:30:54<7:32:04,  6.29s/it]
 19%|█▉        | 1006/5314 [1:31:02<7:53:50,  6.60s/it]
 19%|█▉        | 1007/5314 [1:31:08<7:45:59,  6.49s/it]
 19%|█▉        | 1008/5314 [1:31:19<9:32:46,  7.98s/it]
 19%|█▉        | 1009/5314 [1:31:26<9:03:43,  7.58s/it]
 19%|█▉        | 1010/5314 [1:31:32<8:37:40,  7.22s/it]
 19%|█▉        | 1011/5314 [1:31:40<8:42:31,  7.29s/it]
 19%|█▉        | 1012/5314 [1:31:46<8:18:21,  6.95s/it]
 19%|█▉        | 1013/5314 [1:31:57<9:56:51,  8.33s/it]

Error 84

 19%|█▉        | 1014/5314 [1:31:58<7:14:29,  6.06s/it]
 19%|█▉        | 1015/5314 [1:32:05<7:40:24,  6.43s/it]
 19%|█▉        | 1016/5314 [1:32:12<7:49:55,  6.56s/it]
 19%|█▉        | 1017/5314 [1:32:19<7:59:42,  6.70s/it]
 19%|█▉        | 1018/5314 [1:32:26<7:49:38,  6.56s/it]
 19%|█▉        | 1019/5314 [1:32:33<7:57:29,  6.67s/it]
 19%|█▉        | 1020/5314 [1:32:39<7:49:07,  6.56s/it]
 19%|█▉        | 1021/5314 [1:32:45<7:50:18,  6.57s/it]
 19%|█▉        | 1022/5314 [1:32:52<7:59:49,  6.71s/it]
 19%|█▉        | 1023/5314 [1:32:59<7:49:29,  6.56s/it]
 19%|█▉        | 1024/5314 [1:33:05<7:53:29,  6.62s/it]
 19%|█▉        | 1025/5314 [1:33:14<8:37:30,  7.24s/it]
 19%|█▉        | 1026/5314 [1:33:22<8:48:42,  7.40s/it]
 19%|█▉        | 1027/5314 [1:33:29<8:33:31,  7.19s/it]

Error 85

 19%|█▉        | 1028/5314 [1:33:29<6:10:35,  5.19s/it]

Error 86

 19%|█▉        | 1029/5314 [1:33:30<4:29:21,  3.77s/it]
 19%|█▉        | 1030/5314 [1:33:36<5:23:18,  4.53s/it]
 19%|█▉        | 1031/5314 [1:33:43<6:09:22,  5.17s/it]
 19%|█▉        | 1032/5314 [1:33:53<8:10:52,  6.88s/it]
 19%|█▉        | 1033/5314 [1:34:00<8:00:03,  6.73s/it]
 19%|█▉        | 1034/5314 [1:34:07<8:00:36,  6.74s/it]
 19%|█▉        | 1035/5314 [1:34:16<9:07:17,  7.67s/it]
 19%|█▉        | 1036/5314 [1:34:22<8:33:11,  7.20s/it]
 20%|█▉        | 1037/5314 [1:34:29<8:20:44,  7.02s/it]
 20%|█▉        | 1038/5314 [1:34:35<8:01:30,  6.76s/it]
 20%|█▉        | 1039/5314 [1:34:43<8:26:24,  7.11s/it]
 20%|█▉        | 1040/5314 [1:34:49<8:02:44,  6.78s/it]
 20%|█▉        | 1041/5314 [1:34:56<7:58:49,  6.72s/it]
 20%|█▉        | 1042/5314 [1:35:02<7:55:20,  6.68s/it]
 20%|█▉        | 1043/5314 [1:35:08<7:41:32,  6.48s/it]
 20%|█▉        | 1044/5314 [1:35:15<7:34:21,  6.38s/it]
 20%|█▉        | 1045/5314 [1:35:22<7:57:12,  6.71s/it]
 20%|█▉        | 1046/5314 [1:35:28<7:52:43,  6.65s/it]
 20%|█▉        | 1047/5314 [1:35:34<7:39:04,  6.46s/it]
 20%|█▉        | 1048/5314 [1:35:43<8:30:41,  7.18s/it]
 20%|█▉        | 1049/5314 [1:35:50<8:26:02,  7.12s/it]

Error 87

 20%|█▉        | 1050/5314 [1:35:51<6:00:50,  5.08s/it]
 20%|█▉        | 1051/5314 [1:35:57<6:23:01,  5.39s/it]
 20%|█▉        | 1052/5314 [1:36:08<8:36:02,  7.26s/it]
 20%|█▉        | 1053/5314 [1:36:15<8:18:22,  7.02s/it]
 20%|█▉        | 1054/5314 [1:36:21<8:07:33,  6.87s/it]
 20%|█▉        | 1055/5314 [1:36:29<8:23:03,  7.09s/it]
 20%|█▉        | 1056/5314 [1:36:36<8:27:27,  7.15s/it]
 20%|█▉        | 1057/5314 [1:36:43<8:22:37,  7.08s/it]
 20%|█▉        | 1058/5314 [1:36:51<8:43:47,  7.38s/it]
 20%|█▉        | 1059/5314 [1:36:58<8:36:44,  7.29s/it]
 20%|█▉        | 1060/5314 [1:37:09<9:50:25,  8.33s/it]
 20%|█▉        | 1061/5314 [1:37:16<9:12:30,  7.79s/it]
 20%|█▉        | 1062/5314 [1:37:23<9:11:19,  7.78s/it]
 20%|██        | 1063/5314 [1:37:31<9:14:04,  7.82s/it]

Error 88

 20%|██        | 1064/5314 [1:37:32<6:42:48,  5.69s/it]
 20%|██        | 1065/5314 [1:37:43<8:42:01,  7.37s/it]
 20%|██        | 1066/5314 [1:37:50<8:35:19,  7.28s/it]
 20%|██        | 1067/5314 [1:37:57<8:18:21,  7.04s/it]
 20%|██        | 1068/5314 [1:38:03<8:05:28,  6.86s/it]
 20%|██        | 1069/5314 [1:43:25<119:13:42, 101.11s/it]
 20%|██        | 1070/5314 [1:43:34<86:56:14, 73.75s/it]
 20%|██        | 1071/5314 [1:43:41<63:15:11, 53.67s/it]
 20%|██        | 1072/5314 [1:43:48<46:39:20, 39.59s/it]

Error 89

 20%|██        | 1073/5314 [1:43:48<32:49:11, 27.86s/it]
 20%|██        | 1074/5314 [1:44:00<27:14:44, 23.13s/it]
 20%|██        | 1075/5314 [1:44:08<21:37:51, 18.37s/it]
 20%|██        | 1076/5314 [1:44:14<17:29:13, 14.85s/it]
 20%|██        | 1077/5314 [1:44:25<16:01:11, 13.61s/it]
 20%|██        | 1078/5314 [1:44:33<13:58:00, 11.87s/it]
 20%|██        | 1079/5314 [1:44:40<12:16:51, 10.44s/it]
 20%|██        | 1080/5314 [1:44:46<10:50:30,  9.22s/it]
 20%|██        | 1081/5314 [1:44:53<10:07:03,  8.60s/it]
 20%|██        | 1082/5314 [1:45:00<9:18:38,  7.92s/it]
 20%|██        | 1083/5314 [1:45:07<9:10:53,  7.81s/it]
 20%|██        | 1084/5314 [1:45:14<8:37:47,  7.34s/it]
 20%|██        | 1085/5314 [1:45:20<8:17:54,  7.06s/it]

Error 90

 20%|██        | 1086/5314 [1:45:23<6:47:45,  5.79s/it]
 20%|██        | 1087/5314 [1:45:31<7:27:52,  6.36s/it]
 20%|██        | 1088/5314 [1:45:37<7:37:19,  6.49s/it]
 20%|██        | 1089/5314 [1:45:44<7:49:22,  6.67s/it]
 21%|██        | 1090/5314 [1:45:53<8:21:43,  7.13s/it]
 21%|██        | 1091/5314 [1:45:59<8:05:18,  6.90s/it]
 21%|██        | 1092/5314 [1:46:07<8:27:43,  7.22s/it]
 21%|██        | 1093/5314 [1:46:13<8:14:11,  7.02s/it]
 21%|██        | 1094/5314 [1:46:24<9:38:03,  8.22s/it]
 21%|██        | 1095/5314 [1:46:31<9:08:21,  7.80s/it]
 21%|██        | 1096/5314 [1:46:38<8:39:56,  7.40s/it]
 21%|██        | 1097/5314 [1:46:45<8:34:39,  7.32s/it]
 21%|██        | 1098/5314 [1:46:52<8:19:55,  7.11s/it]
 21%|██        | 1099/5314 [1:46:59<8:25:42,  7.20s/it]
 21%|██        | 1100/5314 [1:47:10<9:33:04,  8.16s/it]
 21%|██        | 1101/5314 [1:47:17<9:23:45,  8.03s/it]
 21%|██        | 1102/5314 [1:47:24<8:58:16,  7.67s/it]
 21%|██        | 1103/5314 [1:47:34<9:46:59,  8.36s/it]
 21%|██        | 1104/5314 [1:47:41<9:21:56,  8.01s/it]
 21%|██        | 1105/5314 [1:47:48<9:00:41,  7.71s/it]
 21%|██        | 1106/5314 [1:47:55<8:43:29,  7.46s/it]
 21%|██        | 1107/5314 [1:48:02<8:31:14,  7.29s/it]
 21%|██        | 1108/5314 [1:48:09<8:31:15,  7.29s/it]
 21%|██        | 1109/5314 [1:48:16<8:28:17,  7.25s/it]
 21%|██        | 1110/5314 [1:48:24<8:30:49,  7.29s/it]
 21%|██        | 1111/5314 [1:48:30<8:19:29,  7.13s/it]
 21%|██        | 1112/5314 [1:48:38<8:26:20,  7.23s/it]
 21%|██        | 1113/5314 [1:48:48<9:21:08,  8.01s/it]
 21%|██        | 1114/5314 [1:49:02<11:38:02,  9.97s/it]
 21%|██        | 1115/5314 [1:49:09<10:23:34,  8.91s/it]
 21%|██        | 1116/5314 [1:49:16<9:55:29,  8.51s/it]
 21%|██        | 1117/5314 [1:49:28<11:05:15,  9.51s/it]
 21%|██        | 1118/5314 [1:49:36<10:26:21,  8.96s/it]
 21%|██        | 1119/5314 [1:49:46<10:58:24,  9.42s/it]

Error 91

 21%|██        | 1120/5314 [1:49:47<7:53:23,  6.77s/it]
 21%|██        | 1121/5314 [1:49:56<8:51:10,  7.60s/it]
 21%|██        | 1122/5314 [1:50:06<9:23:22,  8.06s/it]
 21%|██        | 1123/5314 [1:50:13<9:13:40,  7.93s/it]
 21%|██        | 1124/5314 [1:50:21<9:02:36,  7.77s/it]
 21%|██        | 1125/5314 [1:50:29<9:10:54,  7.89s/it]
 21%|██        | 1126/5314 [1:50:37<9:19:18,  8.01s/it]
 21%|██        | 1127/5314 [1:50:44<8:58:14,  7.71s/it]
 21%|██        | 1128/5314 [1:50:51<8:41:27,  7.47s/it]
 21%|██        | 1129/5314 [1:51:10<12:24:35, 10.68s/it]
 21%|██▏       | 1130/5314 [1:51:24<13:52:21, 11.94s/it]

Error 92

 21%|██▏       | 1131/5314 [1:51:25<9:55:21,  8.54s/it]
 21%|██▏       | 1132/5314 [1:51:49<15:28:27, 13.32s/it]
 21%|██▏       | 1133/5314 [1:51:59<14:08:25, 12.18s/it]
 21%|██▏       | 1134/5314 [1:52:09<13:26:17, 11.57s/it]
 21%|██▏       | 1135/5314 [1:52:18<12:29:03, 10.75s/it]
 21%|██▏       | 1136/5314 [1:52:26<11:35:34,  9.99s/it]
 21%|██▏       | 1137/5314 [1:52:38<12:10:04, 10.49s/it]
 21%|██▏       | 1138/5314 [1:52:50<12:56:27, 11.16s/it]
 21%|██▏       | 1139/5314 [1:52:59<12:14:59, 10.56s/it]

Error 93

 21%|██▏       | 1140/5314 [1:53:00<8:49:51,  7.62s/it]
 21%|██▏       | 1141/5314 [1:53:17<12:04:39, 10.42s/it]

Error 94

 21%|██▏       | 1142/5314 [1:53:18<8:42:56,  7.52s/it]
 22%|██▏       | 1143/5314 [1:53:26<8:59:27,  7.76s/it]
 22%|██▏       | 1144/5314 [1:54:01<18:27:56, 15.94s/it]
 22%|██▏       | 1145/5314 [1:54:10<16:08:08, 13.93s/it]
 22%|██▏       | 1146/5314 [1:54:22<15:26:05, 13.33s/it]
 22%|██▏       | 1147/5314 [1:54:34<14:58:38, 12.94s/it]
 22%|██▏       | 1148/5314 [1:54:42<13:05:19, 11.31s/it]
 22%|██▏       | 1149/5314 [1:54:49<11:39:34, 10.08s/it]
 22%|██▏       | 1150/5314 [1:55:00<11:51:05, 10.25s/it]
 22%|██▏       | 1151/5314 [1:55:11<12:05:32, 10.46s/it]
 22%|██▏       | 1152/5314 [1:55:30<15:16:10, 13.21s/it]
 22%|██▏       | 1153/5314 [1:55:40<13:53:53, 12.02s/it]

Error 95

 22%|██▏       | 1154/5314 [1:55:40<10:01:39,  8.68s/it]
 22%|██▏       | 1155/5314 [1:55:53<11:14:31,  9.73s/it]
 22%|██▏       | 1156/5314 [1:56:05<11:54:35, 10.31s/it]
 22%|██▏       | 1157/5314 [1:56:20<13:42:37, 11.87s/it]
 22%|██▏       | 1158/5314 [1:56:26<11:54:32, 10.32s/it]
 22%|██▏       | 1159/5314 [1:56:39<12:35:08, 10.90s/it]
 22%|██▏       | 1160/5314 [1:56:46<11:21:54,  9.85s/it]
 22%|██▏       | 1161/5314 [1:56:55<10:55:33,  9.47s/it]
 22%|██▏       | 1162/5314 [1:57:05<10:55:02,  9.47s/it]
 22%|██▏       | 1163/5314 [1:57:28<15:52:41, 13.77s/it]
 22%|██▏       | 1164/5314 [1:57:41<15:42:28, 13.63s/it]
 22%|██▏       | 1165/5314 [1:57:52<14:48:09, 12.84s/it]
 22%|██▏       | 1166/5314 [1:58:08<15:46:01, 13.68s/it]
 22%|██▏       | 1167/5314 [1:58:25<17:03:58, 14.82s/it]

MemoryError: Unable to allocate 207. MiB for an array with shape (15, 1806912) and data type object

In [44]:
matches_df['matchId'].tolist()[0]
event_data = requests.get(f"https://apirest.wyscout.com/v3/matches/5539787/events", auth=(username, password))
data = pd.DataFrame(event_data.json()['events'])
data.head()

,id,matchId,matchPeriod,minute,second,matchTimestamp,videoTimestamp,relatedEventId,type,location,team,opponentTeam,player,pass,shot,groundDuel,aerialDuel,infraction,carry,possession
0,1800671870,5539787,1H,0,4,00:00:04.561,6.561177,1.800672e+09,"{'primary': 'pass', 'secondary': ['back_pass',...","{'x': 50, 'y': 51}","{'id': 61422, 'name': 'Bryant Bulldogs', 'form...","{'id': 61833, 'name': 'Chicago State Cougars',...","{'id': 758799, 'name': 'J. Collins', 'position...","{'accurate': True, 'angle': -138, 'height': No...",None,None,None,None,None,"{'id': 1800671870, 'duration': '56.713308', 't..."
1,1800671871,5539787,1H,0,7,00:00:07.122,9.122475,1.800672e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'x': 42, 'y': 39}","{'id': 61422, 'name': 'Bryant Bulldogs', 'form...","{'id': 61833, 'name': 'Chicago State Cougars',...","{'id': 711160, 'name': 'M. Griffin', 'position...","{'accurate': True, 'angle': -45, 'height': Non...",None,None,None,None,None,"{'id': 1800671870, 'duration': '56.713308', 't..."
2,1800671872,5539787,1H,0,9,00:00:09.097,11.097184,1.800672e+09,"{'primary': 'pass', 'secondary': ['forward_pas...","{'x': 59, 'y': 13}","{'id': 61422, 'name': 'Bryant Bulldogs', 'form...","{'id': 61833, 'name': 'Chicago State Cougars',...","{'id': 711161, 'name': 'N. Singer', 'position'...","{'accurate': True, 'angle': 0, 'height': None,...",None,None,None,None,None,"{'id': 1800671870, 'duration': '56.713308', 't..."
3,1800671873,5539787,1H,0,9,00:00:09.357,11.357735,1.800672e+09,"{'primary': 'duel', 'secondary': ['ground_duel...","{'x': 67, 'y': 13}","{'id': 61422, 'name': 'Bryant Bulldogs', 'form...","{'id': 61833, 'name': 'Chicago State Cougars',...","{'id': 758759, 'name': 'C. Bean', 'position': ...",None,None,"{'opponent': {'id': 760662, 'name': 'B. Sanche...",None,None,None,"{'id': 1800671870, 'duration': '56.713308', 't..."
4,1800673166,5539787,1H,0,9,00:00:09.357,11.357735,1.800672e+09,"{'primary': 'duel', 'secondary': ['defensive_d...","{'x': 33, 'y': 87}","{'id': 61833, 'name': 'Chicago State Cougars',...","{'id': 61422, 'name': 'Bryant Bulldogs', 'form...","{'id': 760662, 'name': 'B. Sanchez', 'position...",None,None,"{'opponent': {'id': 758759, 'name': 'C. Bean',...",None,None,None,"{'id': 1800671870, 'duration': '56.713308', 't..."